PropertyValueObjects
    JavaProperties
        rootPackage: string

    HlaProperties
        java: JavaProperties

Properties
    "properties" -> HlaProperties

Enums
    ModuleLanguage
        KOTLIN
        TYPE_SCRIPT

ValueObjects
    ModuleName: string

    GenerateModuleArgs
        moduleName: ModuleName
        language: ModuleLanguage
        hlaFolderPath: Path
        projectPath: Path

Interfaces
    HlaFacade
        generateModule(args: GenerateModuleArgs)
