// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.somemodule.web

import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

import com.some.pkg.somemodule.api.*

@RestController
@RequestMapping("/someInterface")
class SomeInterfaceController(
    private val api: SomeInterface,
) {
    @RequestMapping("/someCommand")
    fun someCommand(@RequestBody request: SomeInterfaceSomeCommandRequest): Unit {
        api.someCommand(request.id, request.amount)
    }

    @RequestMapping("/someQuery")
    fun someQuery(@RequestBody request: SomeInterfaceSomeQueryRequest): SomeInterfaceSomeQueryResponse {
        return SomeInterfaceSomeQueryResponse(api.someQuery(request.id))
    }

    @RequestMapping("/optMethod")
    fun optMethod(@RequestBody request: SomeInterfaceOptMethodRequest): SomeInterfaceOptMethodResponse {
        return SomeInterfaceOptMethodResponse(api.optMethod(request.optId))
    }
}

@RestController
@RequestMapping("/someInterface2")
class SomeInterface2Controller(
    private val api: SomeInterface2,
) {
    @RequestMapping("/referenceInterface")
    fun referenceInterface(@RequestBody request: SomeInterface2ReferenceInterfaceRequest): SomeInterface2ReferenceInterfaceResponse {
        return SomeInterface2ReferenceInterfaceResponse(api.referenceInterface(request.empty))
    }

    @RequestMapping("/referenceOtherInterface")
    fun referenceOtherInterface(@RequestBody request: SomeInterface2ReferenceOtherInterfaceRequest): SomeInterface2ReferenceOtherInterfaceResponse {
        return SomeInterface2ReferenceOtherInterfaceResponse(api.referenceOtherInterface(request.other))
    }

    @RequestMapping("/referenceLegacyType")
    fun referenceLegacyType(@RequestBody request: SomeInterface2ReferenceLegacyTypeRequest): SomeInterface2ReferenceLegacyTypeResponse {
        return SomeInterface2ReferenceLegacyTypeResponse(api.referenceLegacyType(request.legacyType))
    }
}

