// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.somemodule.web

import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

import com.some.pkg.somemodule.api.*
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PostMapping

@RestController
@RequestMapping("/someInterface")
class SomeInterfaceController(
    private val api: SomeInterface,
) {
    @PostMapping("/someEmptyMethod")
    fun someEmptyMethod(): Unit {
        api.someEmptyMethod()
    }

    @PostMapping("/someCommand")
    fun someCommand(@RequestBody request: SomeInterfaceSomeCommandRequest): Unit {
        api.someCommand(request.id, request.amount)
    }

    @PostMapping("/someQuery")
    fun someQuery(@RequestBody request: SomeInterfaceSomeQueryRequest): SomeInterfaceSomeQueryResponse {
        return SomeInterfaceSomeQueryResponse(api.someQuery(request.id))
    }

    @PostMapping("/optMethod")
    fun optMethod(@RequestBody request: SomeInterfaceOptMethodRequest): SomeInterfaceOptMethodResponse {
        return SomeInterfaceOptMethodResponse(api.optMethod(request.optId))
    }
}

@RestController
@RequestMapping("/someInterface2")
class SomeInterface2Controller(
    private val api: SomeInterface2,
) {
    @RequestMapping("/referenceOtherClass")
    fun referenceOtherClass(@RequestBody request: SomeInterface2ReferenceOtherClassRequest): SomeInterface2ReferenceOtherClassResponse {
        return SomeInterface2ReferenceOtherClassResponse(api.referenceOtherClass(request.other))
    }

    @RequestMapping("/referenceLegacyType")
    fun referenceLegacyType(@RequestBody request: SomeInterface2ReferenceLegacyTypeRequest): SomeInterface2ReferenceLegacyTypeResponse {
        return SomeInterface2ReferenceLegacyTypeResponse(api.referenceLegacyType(request.legacyType))
    }
}

