// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Traits;
using B20.Frontend.UiElements;
using SomeModule.Api;
using OtherModule.Api;
using TypesModule.Api;

namespace SomeModule.ViewModel {
    public partial class SomeClassVm {
    }
}