// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.someusermodule.fixtures

import org.assertj.core.api.Assertions.assertThat

import com.some.pkg.someusermodule.api.*

fun assertSomeUserValueObject(given: SomeUserValueObject, expectedInit: ExpectedSomeUserValueObject.() -> Unit) {
    val diff = diffSomeUserValueObject(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}