// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.someusermodule.fixtures

import com.some.pkg.someusermodule.api.*

data class ExpectedSomeUserValueObject(
    var someField: Int? = null,
)
fun diffSomeUserValueObject(given: SomeUserValueObject, expectedInit: ExpectedSomeUserValueObject.() -> Unit, path: String = ""): String {
    val expected = ExpectedSomeUserValueObject().apply(expectedInit)
    val result: MutableList<String> = mutableListOf()

    expected.someField?.let {
        if (given.getSomeField() != it) { result.add("${path}someField ${given.getSomeField()} != ${it}") }
    }

    return result.joinToString("\n")
}