// DO NOT EDIT! Autogenerated by HLA tool

class NoInterfaceId {
    constructor(
        public readonly value: string
    ) {}

    equals(other: NoInterfaceId): boolean {
        return this.value === other.value
    }

    toString(): string {
        return this.value.toString()
    }
}