// DO NOT EDIT! Autogenerated by HLA tool

class SimpleId {
    constructor(
        public readonly value: string
    ) {}

    equals(other: SimpleId): boolean {
        return this.value === other.value
    }

    toString(): string {
        return this.value.toString()
    }
}

class SomeLongWrapper {
    constructor(
        public readonly value: number
    ) {}

    equals(other: SomeLongWrapper): boolean {
        return this.value === other.value
    }

    toString(): string {
        return this.value.toString()
    }

    plus(other: SomeLongWrapper): SomeLongWrapper {
        return new SomeLongWrapper(this.value + other.value);
    }

    minus(other: SomeLongWrapper): SomeLongWrapper {
        return new SomeLongWrapper(this.value - other.value);
    }

    times(amount: number): SomeLongWrapper {
        return new SomeLongWrapper(this.value * amount);
    }
}