ValueObjects
    OtherProperty
        id: OtherId: int
        name: string

    OtherClass
        id: OtherId
        amount: int


DataClasses
    OtherData
        id: OtherId

PropertyKeys
    "otherProperty" -> OtherProperty
    "otherProperties" -> OtherProperty[]

DataKeys
    "otherData" -> OtherData

Interfaces
    OtherInterface
        otherMethod()

Impl
    DataClasses
        OtherImplData
            name: string
    DataKeys
        "otherImplData" -> OtherImplData[]