ValueObjects
    OtherProperty
        id: OtherId: int
        name: string

    OtherClass
        id: OtherId
        amount: int


DataClasses
    OtherData
        id: OtherId

PropertyKeys
    "otherProperty" -> OtherProperty
    "otherProperties" -> OtherProperty[]

DataKeys
    "otherData" -> OtherData

Exceptions
    OtherExtraException

Interfaces
    OtherInterface
        otherMethod()

Web
    PlayFabHandlers
        ExposedInterfaces
            OtherInterface

ViewModel
    Elements
        OtherClassVm
            OtherClass
                id
                amount

    Popups
        OtherPopup
            State
                id: OtherId