Enums
    SomeEnum
        VALUE_A
        VALUE_B

CustomTypes
    DateRangeWrapper
        range: DateRange

Properties
    SomeProperty
        other: OtherProperty

    SomeProperty2
        value: string
        custom: any
        customOpt: any? = empty

Data
    SomeData
        other: OtherData
        custom: any
        customOpt: any?

NamedTypes
    SomeId: string

ValueObjects
    SomeClass
        id: SomeId
        amount: int

    SomeClass2
        id: SomeId
        names: string[]
        ids: SomeId[]
        enabled: bool = true

    SomeClass3
        class2Object: SomeClass2
        someEnum: SomeEnum
        class2List: SomeClass2[] = []

    SomeClass4
        otherId: OtherId
        otherClass: OtherClass
        otherIdList: OtherId[]
        otherClassList: OtherClass[]

    SomeClass5
        date: Date
        dateRange: DateRange
        dateRangeWrapper: DateRangeWrapper
        someProperty: SomeProperty
        otherProperty: OtherProperty

    SomeClass6
        someClassOpt: SomeClass?
        optString: string?
        sameClassList: SomeClass6[] = []

Interfaces
    SomeInterface
        someCommand(id: SomeId, amount: int)
            throws
                SomeException
                Some2Exception
        someQuery(id: SomeId): SomeClass
            throws
                SomeException
        optMethod(optId: SomeId?): SomeClass?