// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.validations.fixtures

import com.github.bratek20.hla.facade.api.*
import com.github.bratek20.hla.facade.fixtures.*
import com.github.bratek20.utils.directory.api.*
import com.github.bratek20.utils.directory.fixtures.*

import com.github.bratek20.hla.validations.api.*

fun propertyValuePath(value: String = "\"propertyName\"/path/to/value"): PropertyValuePath {
    return PropertyValuePath(value)
}

data class ValidationContextDef(
    var path: String = "\"propertyName\"/path/to/value",
)
fun validationContext(init: ValidationContextDef.() -> Unit = {}): ValidationContext {
    val def = ValidationContextDef().apply(init)
    return ValidationContext.create(
        path = PropertyValuePath(def.path),
    )
}

data class ValidationResultDef(
    var ok: Boolean = false,
    var errors: List<String> = emptyList(),
)
fun validationResult(init: ValidationResultDef.() -> Unit = {}): ValidationResult {
    val def = ValidationResultDef().apply(init)
    return ValidationResult.create(
        ok = def.ok,
        errors = def.errors,
    )
}