// DO NOT EDIT! Autogenerated by HLA tool

package src.main.kotlinSkipPatterns.com.some.pkg.webnowrappers.web

import com.github.bratek20.architecture.context.api.ContextBuilder
import com.github.bratek20.architecture.context.api.ContextModule
import com.github.bratek20.infrastructure.httpclient.api.HttpClientConfig
import com.github.bratek20.infrastructure.httpserver.api.WebServerModule

import src.main.kotlinSkipPatterns.com.some.pkg.webnowrappers.api.*
import src.main.kotlinSkipPatterns.com.some.pkg.webnowrappers.web.*

class WebNoWrappersWebClient(
    private val config: HttpClientConfig
): ContextModule {
    override fun apply(builder: ContextBuilder) {
        builder
            .setImplObject(WebNoWrappersWebClientConfig::class.java, WebNoWrappersWebClientConfig(config))
            .setImpl(WebApi::class.java, WebApiWebClient::class.java)
    }
}