// DO NOT EDIT! Autogenerated by HLA tool

package pl.bratek20.hla.writing.fixtures

import pl.bratek20.hla.directory.api.*
import pl.bratek20.hla.directory.fixtures.*
import pl.bratek20.hla.facade.api.*
import pl.bratek20.hla.facade.fixtures.*
import pl.bratek20.hla.generation.api.*
import pl.bratek20.hla.generation.fixtures.*

import pl.bratek20.hla.writing.api.*

data class WriteArgsDef(
    var hlaFolderPath: String = "someValue",
    var generateResult: (GenerateResultDef.() -> Unit) = {},
    var profile: (HlaProfileDef.() -> Unit) = {},
    var onlyUpdate: Boolean = false,
)
fun writeArgs(init: WriteArgsDef.() -> Unit = {}): WriteArgs {
    val def = WriteArgsDef().apply(init)
    return WriteArgs(
        hlaFolderPath = pathCreate(def.hlaFolderPath),
        generateResult = generateResult(def.generateResult),
        profile = hlaProfile(def.profile),
        onlyUpdate = def.onlyUpdate,
    )
}