// DO NOT EDIT! Autogenerated by HLA tool

import { ImportingProperty } from "../../../main/ImportingModule/Api/ValueObjects"
import * as OtherModuleBuilder from "../../OtherModule/Fixtures/Builders"

export interface ImportingPropertyDef {
    other?: OtherModuleBuilder.OtherPropertyDef,
}
export function importingProperty(def?: ImportingPropertyDef): ImportingProperty {
    const final_other = def?.other ?? {}

    return ImportingProperty.create(
        OtherModuleBuilder.otherProperty(final_other),
    )
}
