// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.webnowrappers.web

import com.github.bratek20.infrastructure.httpclient.api.HttpClientFactory

import com.some.pkg.webnowrappers.api.*

class WebApiWebClient(
    factory: HttpClientFactory,
    config: WebNoWrappersWebClientConfig,
): WebApi {
    private val client = factory.create(config.value)

    override fun handleRequest(i: WebRequest): WebResult {
        return client.post("/webApi/handleRequest", WebApiHandleRequestRequest.create(i)).getBody(WebApiHandleRequestResponse::class.java).getValue()
    }
}

