// DO NOT EDIT! Autogenerated by HLA tool

package src.main.kotlinSkipPatterns.com.some.pkg.webnowrappers.fixtures

import org.assertj.core.api.Assertions.assertThat

import src.main.kotlinSkipPatterns.com.some.pkg.webnowrappers.api.*

fun assertWebRequest(given: WebRequest, expectedInit: ExpectedWebRequest.() -> Unit) {
    val diff = diffWebRequest(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertWebResult(given: WebResult, expectedInit: ExpectedWebResult.() -> Unit) {
    val diff = diffWebResult(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}