// DO NOT EDIT! Autogenerated by HLA tool

namespace SomeModule.Web {
    export class SomeInterfaceSomeCommandRequest {
        private id = TODO
        private amount = TODO
        getId(): SomeId {
            return new SomeId(id)
        }
        getAmount(): number {
            return amount
        }
        static create(id: SomeId, amount: number): SomeInterfaceSomeCommandRequest {
            const instance = new SomeInterfaceSomeCommandRequest()
            instance.id = id.value
            instance.amount = amount
            return instance
        }
    }
    export class SomeInterfaceSomeQueryRequest {
        private query = TODO
        getQuery(): SomeQueryInput {
            return query
        }
        static create(query: SomeQueryInput): SomeInterfaceSomeQueryRequest {
            const instance = new SomeInterfaceSomeQueryRequest()
            instance.query = query
            return instance
        }
    }
    export class SomeInterfaceSomeQueryResponse {
        constructor(
            readonly value: SomeClass,
        ) {}
    }
    export class SomeInterfaceOptMethodRequest {
        private optId = TODO
        getOptId(): Optional<SomeId> {
            return Optional.of(optId).map(it => new SomeId(it))
        }
        static create(optId: Optional<SomeId>): SomeInterfaceOptMethodRequest {
            const instance = new SomeInterfaceOptMethodRequest()
            instance.optId = optId.map(it => it.value).orElse(undefined)
            return instance
        }
    }
    export class SomeInterfaceOptMethodResponse {
        constructor(
            readonly value: Optional<SomeClass>,
        ) {}
    }
    export class SomeInterface2ReferenceOtherClassRequest {
        private other = TODO
        getOther(): OtherClass {
            return other
        }
        static create(other: OtherClass): SomeInterface2ReferenceOtherClassRequest {
            const instance = new SomeInterface2ReferenceOtherClassRequest()
            instance.other = other
            return instance
        }
    }
    export class SomeInterface2ReferenceOtherClassResponse {
        constructor(
            readonly value: OtherClass,
        ) {}
    }
    export class SomeInterface2ReferenceLegacyTypeRequest {
        private legacyType = TODO
        getLegacyType(): LegacyType {
            return legacyType
        }
        static create(legacyType: LegacyType): SomeInterface2ReferenceLegacyTypeRequest {
            const instance = new SomeInterface2ReferenceLegacyTypeRequest()
            instance.legacyType = legacyType
            return instance
        }
    }
    export class SomeInterface2ReferenceLegacyTypeResponse {
        constructor(
            readonly value: LegacyType,
        ) {}
    }
}