// DO NOT EDIT! Autogenerated by HLA tool

export class OtherExtraException extends ApiException<OtherExtraException> {
    constructor(
        message: string = ""
    ) {
        super(OtherExtraException, message)
    }
    getTypeName(): string {
        return "OtherExtraException"
    }
}

ExceptionsRegistry.register(OtherExtraException)
