// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.generation.fixtures

import org.assertj.core.api.Assertions.assertThat

import com.github.bratek20.utils.directory.api.*
import com.github.bratek20.utils.directory.fixtures.*
import com.github.bratek20.hla.facade.api.*
import com.github.bratek20.hla.facade.fixtures.*
import com.github.bratek20.hla.parsing.api.*
import com.github.bratek20.hla.parsing.fixtures.*

import com.github.bratek20.hla.generation.api.*

fun assertGeneratedPattern(given: GeneratedPattern, expectedInit: ExpectedGeneratedPattern.() -> Unit) {
    val diff = diffGeneratedPattern(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertGeneratedSubmodule(given: GeneratedSubmodule, expectedInit: ExpectedGeneratedSubmodule.() -> Unit) {
    val diff = diffGeneratedSubmodule(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertGeneratedModule(given: GeneratedModule, expectedInit: ExpectedGeneratedModule.() -> Unit) {
    val diff = diffGeneratedModule(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertGenerateArgs(given: GenerateArgs, expectedInit: ExpectedGenerateArgs.() -> Unit) {
    val diff = diffGenerateArgs(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}