// DO NOT EDIT! Autogenerated by HLA tool

namespace SomeModule.Api {
    const config = new SomeModuleWebClientConfig(
        HttpClientConfig.create(
            EnvVars.Api.Get("BASE_URL"),
            "someServerName",
            Optional.of(HttpClientAuth.create(EnvVars.Api.Get("AUTH")))
        )
    )
}

namespace SomeModule.Api {
    export function someEmptyMethod(c: HandlerContext): void {
        new Web.SomeInterfaceWebClient(c).someEmptyMethod()
    }
    export function someCommand(id: SomeId, amount: number, c: HandlerContext): void {
        new Web.SomeInterfaceWebClient(c).someCommand(id, amount)
    }
    export function someQuery(query: SomeQueryInput, c: HandlerContext): SomeClass {
        return new Web.SomeInterfaceWebClient(c).someQuery(query)
    }
    export function optMethod(optId: Optional<SomeId>, c: HandlerContext): Optional<SomeClass> {
        return new Web.SomeInterfaceWebClient(c).optMethod(optId)
    }
    export function referenceOtherClass(other: OtherClass, c: HandlerContext): OtherClass {
        return new Web.SomeInterface2WebClient(c).referenceOtherClass(other)
    }
    export function referenceLegacyType(legacyType: LegacyType, c: HandlerContext): LegacyType {
        return new Web.SomeInterface2WebClient(c).referenceLegacyType(legacyType)
    }
}