// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.nointerfacesmodule.api

data class NoInterfaceId(
    val value: String
) {
    override fun toString(): String {
        return value.toString()
    }
}