// DO NOT EDIT! Autogenerated by HLA tool

import { Date, DateRange, Tier } from "../../../main/TypesModule/Api/CustomTypes"
import * as CustomTypesMapper from "../../../main/TypesModule/Api/CustomTypesMapper"

export function date(value: string = "01/01/1970 00:00"): Date {
    return CustomTypesMapper.dateCreate(value)
}

export function tier(value: number = 1): Tier {
    return CustomTypesMapper.tierCreate(value)
}

export interface DateRangeDef {
    from?: string,
    to?: string,
}
export function dateRange(def?: DateRangeDef): DateRange {
    const final_from = def?.from ?? "01/01/1970 00:00"
    const final_to = def?.to ?? "01/01/2030 00:00"

    return CustomTypesMapper.dateRangeCreate(
        CustomTypesMapper.dateCreate(final_from),
        CustomTypesMapper.dateCreate(final_to),
    )
}
