// DO NOT EDIT! Autogenerated by HLA tool

namespace SomeModule.Impl {
    export class SomeDimension extends TrackingDimension {
        constructor(
            someClass: SomeClass,
            date_range: DateRange
        ) {
            super()
            this.name = someClass.getId().value
            this.amount = someClass.getAmount()
            this.date_range = SerializedDateRange.fromCustomType(date_range)
        }
        private readonly name: string
        private readonly amount: number
        private readonly date_range: SerializedDateRange
        getTableName(): TrackingTableName {
            return new TrackingTableName("some_dimension")
        }
    }

    export class SomeTrackingEvent extends TrackingEvent {
        constructor(
            some_dimension_id: SomeDimension
        ) {
            super()
            this.some_dimension_id = some_dimension_id
        }
        private readonly some_dimension_id: SomeDimension
        getTableName(): TrackingTableName {
            return new TrackingTableName("some_tracking_event")
        }
    }
}