// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.simplemodule.api

data class SimpleId(
    val value: String
) {
    override fun toString(): String {
        return value.toString()
    }
}

data class SomeLongWrapper(
    val value: Long
) {
    override fun toString(): String {
        return value.toString()
    }

    operator fun plus(other: SomeLongWrapper): SomeLongWrapper {
        return SomeLongWrapper(this.value + other.value)
    }

    operator fun minus(other: SomeLongWrapper): SomeLongWrapper {
        return SomeLongWrapper(this.value - other.value)
    }

    operator fun times(other: SomeLongWrapper): SomeLongWrapper {
        return SomeLongWrapper(this.value * other.value)
    }
}