// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.simplemodule.api

data class SimpleId(
    val value: String
) {
    override fun toString(): String {
        return value.toString()
    }
}

data class SomeLongWrapper(
    val value: Long
) {
    override fun toString(): String {
        return value.toString()
    }

    operator fun plus(other: SomeLongWrapper): SomeLongWrapper {
        return SomeLongWrapper(this.value + other.value)
    }

    operator fun minus(other: SomeLongWrapper): SomeLongWrapper {
        return SomeLongWrapper(this.value - other.value)
    }

    operator fun times(amount: Int): SomeLongWrapper {
        return SomeLongWrapper(this.value * amount)
    }
}

data class UniqueIdEntry(
    private val id: String,
) {
    fun getId(): String {
        return this.id
    }

    companion object {
        fun create(
            id: String,
        ): UniqueIdEntry {
            return UniqueIdEntry(
                id = id,
            )
        }
    }
}