// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.webnowrappers.fixtures

import com.some.pkg.webnowrappers.api.*

data class ExpectedWebRequest(
    var inputField: Int? = null,
)
fun diffWebRequest(given: WebRequest, expectedInit: ExpectedWebRequest.() -> Unit, path: String = ""): String {
    val expected = ExpectedWebRequest().apply(expectedInit)
    val result: MutableList<String> = mutableListOf()

    expected.inputField?.let {
        if (given.getInputField() != it) { result.add("${path}inputField ${given.getInputField()} != ${it}") }
    }

    return result.joinToString("\n")
}

data class ExpectedWebResult(
    var outputField: Int? = null,
)
fun diffWebResult(given: WebResult, expectedInit: ExpectedWebResult.() -> Unit, path: String = ""): String {
    val expected = ExpectedWebResult().apply(expectedInit)
    val result: MutableList<String> = mutableListOf()

    expected.outputField?.let {
        if (given.getOutputField() != it) { result.add("${path}outputField ${given.getOutputField()} != ${it}") }
    }

    return result.joinToString("\n")
}