// DO NOT EDIT! Autogenerated by HLA tool

package src.main.kotlinSkipPatterns.com.some.pkg.typesmodule.fixtures

import org.assertj.core.api.Assertions.assertThat

import src.main.kotlinSkipPatterns.com.some.pkg.typesmodule.api.*

fun assertDate(given: Date, expected: String) {
    val diff = diffDate(given, expected)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}


fun assertTier(given: Tier, expected: Int) {
    val diff = diffTier(given, expected)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertDateRange(given: DateRange, expectedInit: ExpectedDateRange.() -> Unit) {
    val diff = diffDateRange(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}