// DO NOT EDIT! Autogenerated by HLA tool

package src.main.kotlinSkipPatterns.com.some.pkg.typesmodule.fixtures

import src.main.kotlinSkipPatterns.com.some.pkg.typesmodule.api.*

fun date(value: String = "01/01/1970 00:00"): Date {
    return dateCreate(value)
}

fun tier(value: Int = 1): Tier {
    return tierCreate(value)
}

data class DateRangeDef(
    var from: String = "01/01/1970 00:00",
    var to: String = "01/01/2030 00:00",
)
fun dateRange(init: DateRangeDef.() -> Unit = {}): DateRange {
    val def = DateRangeDef().apply(init)
    return dateRangeCreate(
        from = dateCreate(def.from),
        to = dateCreate(def.to),
    )
}