// DO NOT EDIT! Autogenerated by HLA tool

package src.main.kotlinSkipPatterns.com.some.pkg.someusermodule.api

import src.main.kotlinSkipPatterns.com.some.pkg.somemodule.api.*

class SomeUserIdValues {
    companion object {
        val UserValue = SomeId("UserValue")
    }
}