// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.tracking.api

import com.github.bratek20.hla.definitions.api.*

data class TableDefinition(
    private val name: String,
    private val attributes: List<Attribute>,
    private val exposedClasses: List<DependentConceptDefinition>,
    private val fields: List<FieldDefinition>,
) {
    fun getName(): String {
        return this.name
    }

    fun getAttributes(): List<Attribute> {
        return this.attributes
    }

    fun getExposedClasses(): List<DependentConceptDefinition> {
        return this.exposedClasses
    }

    fun getFields(): List<FieldDefinition> {
        return this.fields
    }

    companion object {
        fun create(
            name: String,
            attributes: List<Attribute>,
            exposedClasses: List<DependentConceptDefinition>,
            fields: List<FieldDefinition>,
        ): TableDefinition {
            return TableDefinition(
                name = name,
                attributes = attributes,
                exposedClasses = exposedClasses,
                fields = fields,
            )
        }
    }
}

data class TrackingSubmoduleDefinition(
    private val attributes: List<Attribute>,
    private val dimensions: TableDefinition,
    private val events: TableDefinition,
) {
    fun getAttributes(): List<Attribute> {
        return this.attributes
    }

    fun getDimensions(): TableDefinition {
        return this.dimensions
    }

    fun getEvents(): TableDefinition {
        return this.events
    }

    companion object {
        fun create(
            attributes: List<Attribute>,
            dimensions: TableDefinition,
            events: TableDefinition,
        ): TrackingSubmoduleDefinition {
            return TrackingSubmoduleDefinition(
                attributes = attributes,
                dimensions = dimensions,
                events = events,
            )
        }
    }
}