// DO NOT EDIT! Autogenerated by HLA tool

package src.main.kotlinSkipPatterns.com.some.pkg.someusermodule.fixtures

import src.main.kotlinSkipPatterns.com.some.pkg.someusermodule.api.*

data class SomeUserValueObjectDef(
    var someField: Int = 0,
)
fun someUserValueObject(init: SomeUserValueObjectDef.() -> Unit = {}): SomeUserValueObject {
    val def = SomeUserValueObjectDef().apply(init)
    return SomeUserValueObject.create(
        someField = def.someField,
    )
}