// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.generation.api
enum class SubmoduleName {
    Api,
    Impl,
    Web,
    ViewModel,
    Context,
    Fixtures,
    Tests,
}

enum class PatternName {
    Enums,
    ValueObjects,
    DataClasses,
    DataKeys,
    PropertyKeys,
    Interfaces,
    Exceptions,
    CustomTypes,
    CustomTypesMapper,
    SerializedCustomTypes,
    Logic,
    WebCommon,
    WebServer,
    WebClient,
    PlayFabHandlers,
    GeneratedElements,
    Impl,
    Web,
    Builders,
    Diffs,
    Asserts,
    Mocks,
    ImplTest,
}