// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.generation.api

import com.github.bratek20.utils.directory.api.*
import com.github.bratek20.hla.facade.api.*
import com.github.bratek20.hla.parsing.api.*

enum class SubmoduleName {
    Api,
    Impl,
    Web,
    ViewModel,
    View,
    Prefabs,
    Context,
    Fixtures,
    Tests,
    Examples,
    Menu,
}

enum class PatternName {
    Primitives,
    Enums,
    ValueObjects,
    DataClasses,
    DataKeys,
    PropertyKeys,
    Interfaces,
    Exceptions,
    Events,
    CustomTypes,
    CustomTypesMapper,
    SerializedCustomTypes,
    Undefined,
    Logic,
    Track,
    InitSql,
    ImplContext,
    WebCommon,
    WebServer,
    WebClient,
    PlayFabHandlers,
    WebServerContext,
    WebClientContext,
    GeneratedElements,
    ElementsLogic,
    GeneratedWindows,
    WindowsLogic,
    GeneratedPopups,
    PopupsLogic,
    ViewModelContext,
    ElementsView,
    PrefabBlueprints,
    Builders,
    Diffs,
    Asserts,
    Mocks,
    ImplTest,
    HandlersExamples,
    TitleDataExamples,
    PlayerDataExamples,
    Menu,
}