// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.generation.api

import com.github.bratek20.hla.directory.api.*
import com.github.bratek20.hla.facade.api.*
import com.github.bratek20.hla.parsing.api.*

interface ModuleGenerator {
    @Throws(
        UnknownTypeException::class,
    )
    fun generate(args: GenerateArgs): GenerateResult
}