// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.typesworld.api
enum class WorldTypeKind {
    Primitive,
    ClassType,
    GenericWrapper,
    ConcreteWrapper,
    GenericParametrizedClass,
    ConcreteParametrizedClass,
}