// DO NOT EDIT! Autogenerated by HLA tool

namespace SimpleModule.Builder {
    export function simpleId(value: string = "someValue"): SimpleId {
        return new SimpleId(value)
    }

    export function someLongWrapper(value: number = 0): SomeLongWrapper {
        return new SomeLongWrapper(value)
    }

    export interface UniqueIdEntryDef {
        id?: string,
    }
    export function uniqueIdEntry(def?: UniqueIdEntryDef): UniqueIdEntry {
        const final_id = def?.id ?? "someValue"

        return UniqueIdEntry.create(
            final_id,
        )
    }
}