// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.queries.fixtures

import com.github.bratek20.hla.definitions.api.*
import com.github.bratek20.hla.definitions.fixtures.*
import com.github.bratek20.hla.parsing.api.*
import com.github.bratek20.hla.parsing.fixtures.*

import com.github.bratek20.hla.queries.api.*

data class ExpectedModuleDependency(
    var group: (ExpectedModuleGroup.() -> Unit)? = null,
    var module: (ExpectedModuleDefinition.() -> Unit)? = null,
)
fun diffModuleDependency(given: ModuleDependency, expectedInit: ExpectedModuleDependency.() -> Unit, path: String = ""): String {
    val expected = ExpectedModuleDependency().apply(expectedInit)
    val result: MutableList<String> = mutableListOf()

    expected.group?.let {
        if (diffModuleGroup(given.getGroup(), it) != "") { result.add(diffModuleGroup(given.getGroup(), it, "${path}group.")) }
    }

    expected.module?.let {
        if (diffModuleDefinition(given.getModule(), it) != "") { result.add(diffModuleDefinition(given.getModule(), it, "${path}module.")) }
    }

    return result.joinToString("\n")
}