// DO NOT EDIT! Autogenerated by HLA tool

package src.main.kotlinSkipPatterns.com.some.pkg.someusermodule.web

import com.github.bratek20.infrastructure.httpclient.api.HttpClientFactory

import src.main.kotlinSkipPatterns.com.some.pkg.someusermodule.api.*

import src.main.kotlinSkipPatterns.com.some.pkg.somemodule.api.*

class SomeUserInterfaceWebClient(
    factory: HttpClientFactory,
    config: SomeUserModuleWebClientConfig,
): SomeUserInterface {
    private val client = factory.create(config.value)

    override fun someMethod(): Unit {
        client.post("/someUserInterface/someMethod", null)
    }
}

