// DO NOT EDIT! Autogenerated by HLA tool

package src.main.kotlinSkipPatterns.com.some.pkg.someusermodule.web

import com.github.bratek20.infrastructure.httpclient.api.HttpClientConfig

import src.main.kotlinSkipPatterns.com.some.pkg.someusermodule.api.*

class SomeUserModuleWebClientConfig(
    val value: HttpClientConfig
) {
}