// DO NOT EDIT! Autogenerated by HLA tool

package src.main.kotlinSkipPatterns.com.some.pkg.othermodule.fixtures

import org.assertj.core.api.Assertions.assertThat

import src.main.kotlinSkipPatterns.com.some.pkg.othermodule.api.*

fun assertOtherId(given: OtherId, expected: Int) {
    val diff = diffOtherId(given, expected)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertOtherProperty(given: OtherProperty, expectedInit: ExpectedOtherProperty.() -> Unit) {
    val diff = diffOtherProperty(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertOtherClass(given: OtherClass, expectedInit: ExpectedOtherClass.() -> Unit) {
    val diff = diffOtherClass(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertOtherClassWIthUniqueId(given: OtherClassWIthUniqueId, expectedInit: ExpectedOtherClassWIthUniqueId.() -> Unit) {
    val diff = diffOtherClassWIthUniqueId(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertOtherData(given: OtherData, expectedInit: ExpectedOtherData.() -> Unit) {
    val diff = diffOtherData(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}