//detailed
DataClasses
    SomeData
        value: int

DataKeys
    "someData" -> SomeData

//concise
Data
    SomeElementData
        id: SomeId

    "someElementsData" -> SomeElementData[]

//detailed
ValueObjects
    SomeConfig
        enabled: bool

PropertyKeys
    "someConfig" -> SomeConfig

//concise
Properties
    SomeProperty
        name: string

    "someProperties" -> SomeProperty[]

Impl
    //detailed
    DataClasses
        SomeImplData
            value: int

    DataKeys
        "someImplData" -> SomeImplData

    //concise
    Data
        SomeElementImplData
            id: SomeId

        "someElementsImplData" -> SomeElementImplData[]