// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using System.Linq;
using B20.Ext;
using B20.ViewModel.UiElements.Api;
using B20.ViewModel.Windows.Api;
using B20.ViewModel.Popups.Api;
using SomeModule.Api;
using OtherModule.Api;
using OtherModule.ViewModel;
using TypesModule.Api;

namespace SomeModule.ViewModel {
    public class SomePopupState {
        public SomeId SomeId { get; }

        public SomePopupState(
            SomeId someId
        ) {
            SomeId = someId;
        }
    }

    public partial class SomePopup: Popup<SomePopupState> {
        public SomeClassVm SomeClassVm { get; set; }
    }
}