// DO NOT EDIT! Autogenerated by HLA tool

namespace OtherModule {
    export function diffOtherId(given: OtherId, expected: number, path: string = ""): string {
        if (given.getValue() != expected) { return `${path}value ${given.getValue()} != ${expected}` }
        return ""
    }

    export interface ExpectedOtherProperty {
        id?: number,
        name?: string,
    }
    export function diffOtherProperty(given: OtherProperty, expected: ExpectedOtherProperty, path: string = ""): string {
        const result: string[] = []

        if (expected.id !== undefined) {
            if (diffOtherId(given.getId(), expected.id) != "") { result.push(diffOtherId(given.getId(), expected.id, `${path}id.`)) }
        }

        if (expected.name !== undefined) {
            if (given.getName() != expected.name) { result.push(`${path}name ${given.getName()} != ${expected.name}`) }
        }

        return result.join("\n")
    }

    export interface ExpectedOtherClass {
        id?: number,
        amount?: number,
    }
    export function diffOtherClass(given: OtherClass, expected: ExpectedOtherClass, path: string = ""): string {
        const result: string[] = []

        if (expected.id !== undefined) {
            if (diffOtherId(given.getId(), expected.id) != "") { result.push(diffOtherId(given.getId(), expected.id, `${path}id.`)) }
        }

        if (expected.amount !== undefined) {
            if (given.getAmount() != expected.amount) { result.push(`${path}amount ${given.getAmount()} != ${expected.amount}`) }
        }

        return result.join("\n")
    }

    export interface ExpectedOtherClassWIthUniqueId {
        uniqueId?: string,
    }
    export function diffOtherClassWIthUniqueId(given: OtherClassWIthUniqueId, expected: ExpectedOtherClassWIthUniqueId, path: string = ""): string {
        const result: string[] = []

        if (expected.uniqueId !== undefined) {
            if (given.getUniqueId() != expected.uniqueId) { result.push(`${path}uniqueId ${given.getUniqueId()} != ${expected.uniqueId}`) }
        }

        return result.join("\n")
    }

    export interface ExpectedOtherData {
        id?: number,
    }
    export function diffOtherData(given: OtherData, expected: ExpectedOtherData, path: string = ""): string {
        const result: string[] = []

        if (expected.id !== undefined) {
            if (diffOtherId(given.getId(), expected.id) != "") { result.push(diffOtherId(given.getId(), expected.id, `${path}id.`)) }
        }

        return result.join("\n")
    }
}