// DO NOT EDIT! Autogenerated by HLA tool

namespace OtherModule.Builder {
    export function otherId(id: number = 0): OtherId {
        return new OtherId(id)
    }

    export interface OtherPropertyDef {
        id?: number,
        name?: string,
    }
    export function otherProperty(def?: OtherPropertyDef): OtherProperty {
        const id = def?.id ?? 0
        const name = def?.name ?? "someValue"

        return OtherProperty.create(
            new OtherId(id),
            name,
        )
    }

    export interface OtherClassDef {
        id?: number,
        amount?: number,
    }
    export function otherClass(def?: OtherClassDef): OtherClass {
        const id = def?.id ?? 0
        const amount = def?.amount ?? 0

        return OtherClass.create(
            new OtherId(id),
            amount,
        )
    }

    export interface OtherDataDef {
        id?: number,
    }
    export function otherData(def?: OtherDataDef): OtherData {
        const id = def?.id ?? 0

        return OtherData.create(
            new OtherId(id),
        )
    }
}