// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.prefabcreator.api

interface PrefabCreatorApi {
    fun startModulePrefabs(modulesPath: String, moduleName: String): Unit

    fun deleteModulePrefabs(modulesPath: String, moduleName: String): Unit
}