// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.prefabcreator.api

data class PrefabChildBlueprint(
    private val prefabPath: String,
    private val viewType: String,
    private val name: String,
) {
    fun getPrefabPath(): String {
        return this.prefabPath
    }

    fun getViewType(): String {
        return this.viewType
    }

    fun getName(): String {
        return this.name
    }

    companion object {
        fun create(
            prefabPath: String,
            viewType: String,
            name: String,
        ): PrefabChildBlueprint {
            return PrefabChildBlueprint(
                prefabPath = prefabPath,
                viewType = viewType,
                name = name,
            )
        }
    }
}

data class PrefabBlueprint(
    private val prefabName: String,
    private val viewType: String,
    private val children: List<PrefabChildBlueprint>,
) {
    fun getPrefabName(): String {
        return this.prefabName
    }

    fun getViewType(): String {
        return this.viewType
    }

    fun getChildren(): List<PrefabChildBlueprint> {
        return this.children
    }

    companion object {
        fun create(
            prefabName: String,
            viewType: String,
            children: List<PrefabChildBlueprint>,
        ): PrefabBlueprint {
            return PrefabBlueprint(
                prefabName = prefabName,
                viewType = viewType,
                children = children,
            )
        }
    }
}