// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.prefabcreator.api

data class PrefabChildBlueprint(
    private val name: String,
    private val viewType: String,
) {
    fun getName(): String {
        return this.name
    }

    fun getViewType(): String {
        return this.viewType
    }

    companion object {
        fun create(
            name: String,
            viewType: String,
        ): PrefabChildBlueprint {
            return PrefabChildBlueprint(
                name = name,
                viewType = viewType,
            )
        }
    }
}

data class PrefabBlueprint(
    private val blueprintType: String,
    private val name: String,
    private val viewType: String,
    private val creationOrder: Int,
    private val children: List<PrefabChildBlueprint> = emptyList(),
    private val elementViewType: String? = null,
) {
    fun getBlueprintType(): BlueprintType {
        return BlueprintType.valueOf(this.blueprintType)
    }

    fun getName(): String {
        return this.name
    }

    fun getViewType(): String {
        return this.viewType
    }

    fun getCreationOrder(): Int {
        return this.creationOrder
    }

    fun getChildren(): List<PrefabChildBlueprint> {
        return this.children
    }

    fun getElementViewType(): String? {
        return this.elementViewType
    }

    companion object {
        fun create(
            blueprintType: BlueprintType,
            name: String,
            viewType: String,
            creationOrder: Int,
            children: List<PrefabChildBlueprint> = emptyList(),
            elementViewType: String? = null,
        ): PrefabBlueprint {
            return PrefabBlueprint(
                blueprintType = blueprintType.name,
                name = name,
                viewType = viewType,
                creationOrder = creationOrder,
                children = children,
                elementViewType = elementViewType,
            )
        }
    }
}