// DO NOT EDIT! Autogenerated by HLA tool

namespace SomeUserModule.Builder {
    export interface SomeUserValueObjectDef {
        someField?: number,
    }
    export function someUserValueObject(def?: SomeUserValueObjectDef): SomeUserValueObject {
        const final_someField = def?.someField ?? 0

        return SomeUserValueObject.create(
            final_someField,
        )
    }
}