// DO NOT EDIT! Autogenerated by HLA tool

using Some.Pkg.OtherModule.Api;

namespace OtherModule.Fixtures
{
    public static class OtherModuleBuilders
    {
        public static OtherId BuildOtherId(int value = 0)
        {
            return new OtherId(value);
        }

        public class OtherPropertyDef
        {
            public int Id { get; set; } = 0;
            public string Name { get; set; } = "someValue";
        }
        public static OtherProperty BuildOtherProperty(Action<OtherPropertyDef> init = () => {})
        {
            var def = new OtherPropertyDef();
            init.Invoke(def);
            return OtherProperty.Create(
                id: BuildOtherId(def.Id),
                name: def.Name
            );
        }
    }
}
