// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using System.Linq;
using B20.Ext;
using OtherModule.Api;

namespace OtherModule.Fixtures {
    public class OtherModuleBuilders {
        public class OtherPropertyDef {
            public int Id { get; set; } = 0;
            public string Name { get; set; } = "someValue";
        }
        public static OtherId BuildOtherId(int value = 0) {
            return new OtherId(value);
        }
        public static OtherProperty BuildOtherProperty(Action<OtherPropertyDef> init = () => {}) {
            var def = new OtherPropertyDef();
            init.Invoke(def);
            return OtherProperty.Create(OtherModuleBuilders.BuildOtherId(def.Id), def.Name);
        }
    }
}