// DO NOT EDIT! Autogenerated by HLA tool

namespace SimpleModule {
    export function diffSimpleId(given: SimpleId, expected: string, path: string = ""): string {
        if (given.getValue() != expected) { return `${path}value ${given.getValue()} != ${expected}` }
        return ""
    }

    export function diffSomeLongWrapper(given: SomeLongWrapper, expected: number, path: string = ""): string {
        if (given.getValue() != expected) { return `${path}value ${given.getValue()} != ${expected}` }
        return ""
    }

    export interface ExpectedUniqueIdEntry {
        id?: string,
    }
    export function diffUniqueIdEntry(given: UniqueIdEntry, expected: ExpectedUniqueIdEntry, path: string = ""): string {
        const result: string[] = []

        if (expected.id !== undefined) {
            if (given.getId() != expected.id) { result.push(`${path}id ${given.getId()} != ${expected.id}`) }
        }

        return result.join("\n")
    }
}