// DO NOT EDIT! Autogenerated by HLA tool

package pl.bratek20.hla.directory.api

data class File(
    val name: FileName,
    val content: FileContent,
)

data class Directory(
    val name: DirectoryName,
    val files: List<File> = emptyList(),
    val directories: List<Directory> = emptyList(),
)

data class CompareResult(
    val same: Boolean,
    val differences: List<String>,
)