// DO NOT EDIT! Autogenerated by HLA tool

class DateRangeProperty {
    private from = STRING
    private to = STRING

    static create(
        from: string,
        to: string,
    ): DateRangeProperty {
        const instance = new DateRangeProperty()
        instance.from = from
        instance.to = to
        return instance
    }

    getFrom(): Date {
        return TypesModule.CustomTypesMapper.dateCreate(this.from)
    }

    getTo(): Date {
        return TypesModule.CustomTypesMapper.dateCreate(this.to)
    }
}