// DO NOT EDIT! Autogenerated by HLA tool

class DateRangeProperty {
    from = STRING
    to = STRING

    static create(
        from: Date,
        to: Date,
    ): DateRangeProperty {
        const instance = new DateRangeProperty()
        instance.from = TypesModule.CustomTypesMapper.dateGetValue(from)
        instance.to = TypesModule.CustomTypesMapper.dateGetValue(to)
        return instance
    }

    getFrom(): Date {
        return TypesModule.CustomTypesMapper.dateCreate(this.from)
    }

    getTo(): Date {
        return TypesModule.CustomTypesMapper.dateCreate(this.to)
    }
}