// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.hlatypesworld.api

import com.github.bratek20.hla.definitions.api.*
import com.github.bratek20.hla.parsing.api.*

interface HlaTypesWorldApi {
    fun populate(group: ModuleGroup): Unit
}

interface HlaTypesWorldPopulator {
    fun getOrder(): Int

    fun populate(modules: List<ModuleDefinition>): Unit
}