// DO NOT EDIT! Autogenerated by HLA tool

namespace OtherModule.Menu {
    export function initOtherModuleMenu(libraryPrefix: string | undefined) {
        const builder = new MenuBuilder("OtherModule", libraryPrefix)
        builder.addNamespaced("Other Method", "OtherModule.Menu", otherMethod).build()
    }

    export function otherMethod() {
        Woh.menuDecorator((c: any) => { OtherModule.Api.otherMethod.otherMethod(c) })
    }
}