// DO NOT EDIT! Autogenerated by HLA tool

import { SomeId, SomeOtherId } from "./ValueObjects"

export class SomeIdValues {
    static readonly SomeValue = new SomeId("SomeValue")
    static readonly OtherValue = new SomeId("OtherValue")
}

export class SomeOtherIdValues {
    static readonly ThirdValue = new SomeOtherId("ThirdValue")
}
