// DO NOT EDIT! Autogenerated by HLA tool

namespace SomeModule.Assert {
    export function someId(given: SomeId, expected: string) {
        const diff = diffSomeId(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function someIntWrapper(given: SomeIntWrapper, expected: number) {
        const diff = diffSomeIntWrapper(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function someId2(given: SomeId2, expected: number) {
        const diff = diffSomeId2(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function someClass(given: SomeClass, expected: ExpectedSomeClass) {
        const diff = diffSomeClass(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function someClass2(given: SomeClass2, expected: ExpectedSomeClass2) {
        const diff = diffSomeClass2(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function someClass3(given: SomeClass3, expected: ExpectedSomeClass3) {
        const diff = diffSomeClass3(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function someClass4(given: SomeClass4, expected: ExpectedSomeClass4) {
        const diff = diffSomeClass4(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function someClass5(given: SomeClass5, expected: ExpectedSomeClass5) {
        const diff = diffSomeClass5(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function someClass6(given: SomeClass6, expected: ExpectedSomeClass6) {
        const diff = diffSomeClass6(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function classHavingOptList(given: ClassHavingOptList, expected: ExpectedClassHavingOptList) {
        const diff = diffClassHavingOptList(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function classHavingOptSimpleVo(given: ClassHavingOptSimpleVo, expected: ExpectedClassHavingOptSimpleVo) {
        const diff = diffClassHavingOptSimpleVo(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function recordClass(given: RecordClass, expected: ExpectedRecordClass) {
        const diff = diffRecordClass(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function classWithOptExamples(given: ClassWithOptExamples, expected: ExpectedClassWithOptExamples) {
        const diff = diffClassWithOptExamples(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function classWithEnumList(given: ClassWithEnumList, expected: ExpectedClassWithEnumList) {
        const diff = diffClassWithEnumList(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function classWithBoolField(given: ClassWithBoolField, expected: ExpectedClassWithBoolField) {
        const diff = diffClassWithBoolField(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function someQueryInput(given: SomeQueryInput, expected: ExpectedSomeQueryInput) {
        const diff = diffSomeQueryInput(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function someHandlerInput(given: SomeHandlerInput, expected: ExpectedSomeHandlerInput) {
        const diff = diffSomeHandlerInput(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function someHandlerOutput(given: SomeHandlerOutput, expected: ExpectedSomeHandlerOutput) {
        const diff = diffSomeHandlerOutput(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function someProperty(given: SomeProperty, expected: ExpectedSomeProperty) {
        const diff = diffSomeProperty(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function someProperty2(given: SomeProperty2, expected: ExpectedSomeProperty2) {
        const diff = diffSomeProperty2(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function somePropertyEntry(given: SomePropertyEntry, expected: ExpectedSomePropertyEntry) {
        const diff = diffSomePropertyEntry(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function someReferencingProperty(given: SomeReferencingProperty, expected: ExpectedSomeReferencingProperty) {
        const diff = diffSomeReferencingProperty(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function dateRangeWrapper(given: DateRangeWrapper, expected: ExpectedDateRangeWrapper) {
        const diff = diffDateRangeWrapper(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function someData(given: SomeData, expected: ExpectedSomeData) {
        const diff = diffSomeData(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function someData2(given: SomeData2, expected: ExpectedSomeData2) {
        const diff = diffSomeData2(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function someEvent(given: SomeEvent, expected: ExpectedSomeEvent) {
        const diff = diffSomeEvent(given, expected)
        AssertEquals(diff, "", diff)
    }
}