// DO NOT EDIT! Autogenerated by HLA tool

package src.main.kotlinSkipPatterns.com.some.pkg.moduleonlyformocksargs.api

data class MockArg(
    val value: String
) {
    override fun toString(): String {
        return value.toString()
    }
}