// DO NOT EDIT! Autogenerated by HLA tool

package src.main.kotlinSkipPatterns.com.some.pkg.somemodule.api

import src.main.kotlinSkipPatterns.com.some.pkg.moduleonlyformocksargs.api.*
import src.main.kotlinSkipPatterns.com.some.pkg.othermodule.api.*
import src.main.kotlinSkipPatterns.com.some.pkg.simplemodule.api.*
import src.main.kotlinSkipPatterns.com.some.pkg.someusermodule.api.*
import src.main.kotlinSkipPatterns.com.some.pkg.typesmodule.api.*

class SomeIdValues {
    companion object {
        val SomeValue = SomeId("SomeValue")
        val OtherValue = SomeId("OtherValue")
    }
}

class SomeOtherIdValues {
    companion object {
        val ThirdValue = SomeOtherId("ThirdValue")
    }
}