// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using System.Linq;
using B20.Ext;
using OtherModule.Api;

namespace ImportingModule.Api {
    public class ImportingProperty: ValueObject {
        readonly OtherProperty other;

        public ImportingProperty(
            OtherProperty other
        ) {
            this.other = other;
        }
        public OtherProperty GetOther() {
            return other;
        }
        public static ImportingProperty Create(OtherProperty other) {
            return new ImportingProperty(other);
        }
    }
}