// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.queries.api

import com.github.bratek20.hla.definitions.api.*
import com.github.bratek20.hla.parsing.api.*

data class ModuleDependency(
    private val group: ModuleGroup,
    private val module: ModuleDefinition,
) {
    fun getGroup(): ModuleGroup {
        return this.group
    }

    fun getModule(): ModuleDefinition {
        return this.module
    }

    companion object {
        fun create(
            group: ModuleGroup,
            module: ModuleDefinition,
        ): ModuleDependency {
            return ModuleDependency(
                group = group,
                module = module,
            )
        }
    }
}