package com.github.bratek20.hla.tracking.impl

import com.github.bratek20.codebuilder.builders.*
import com.github.bratek20.codebuilder.core.CodeBuilder
import com.github.bratek20.codebuilder.core.Kotlin
import com.github.bratek20.codebuilder.types.TypeBuilder
import com.github.bratek20.codebuilder.types.typeName
import com.github.bratek20.hla.apitypes.api.ApiTypeFactory
import com.github.bratek20.hla.apitypes.impl.ComplexStructureApiType
import com.github.bratek20.hla.attributes.getAttributeValue
import com.github.bratek20.hla.definitions.api.DependencyConceptDefinition
import com.github.bratek20.hla.definitions.api.FieldDefinition
import com.github.bratek20.hla.definitions.api.MappedField
import com.github.bratek20.hla.definitions.api.TypeDefinition
import com.github.bratek20.hla.facade.api.ModuleLanguage
import com.github.bratek20.hla.generation.api.PatternName
import com.github.bratek20.hla.generation.api.SubmoduleName
import com.github.bratek20.hla.generation.impl.core.PatternGenerator
import com.github.bratek20.hla.generation.impl.core.PerFileOperations
import com.github.bratek20.hla.hlatypesworld.api.asHla
import com.github.bratek20.hla.tracking.api.TableDefinition
import com.github.bratek20.hla.typesworld.api.TypesWorldApi
import com.github.bratek20.hla.typesworld.api.WorldTypeName
import com.github.bratek20.hla.typesworld.api.getField
import com.github.bratek20.utils.directory.api.File
import com.github.bratek20.utils.directory.api.FileContent
import com.github.bratek20.utils.directory.api.FileName
import com.github.bratek20.utils.pascalToCamelCase


class InitSqlGenerator: PatternGenerator() {
    override fun patternName(): PatternName {
        return PatternName.InitSql
    }

    override fun supportsCodeBuilder() = true

    override fun shouldGenerate(): Boolean {
        return c.language.name() == ModuleLanguage.TYPE_SCRIPT &&
                c.module.getTrackingSubmodule() != null
    }
    
    override fun getFiles(): List<File> {
        val content = CodeBuilder(Kotlin())
            .line("-- Autogenerated by HLA tool")
            .emptyLine()
            .line("CREATE TABLE some_dimension (")
            .line(");")
            .emptyLine()
            .line("CREATE TABLE some_tracking_event (")
            .line(") INHERITS (event);")
            .line("ALTER TYPE event_type ADD VALUE 'some_tracking_event';")
            .build()

        return listOf(
            File.create(
                name = FileName("0XX_some_module_init.sql"),
                content = FileContent.fromString(content)
            )
        )
    }
}