// DO NOT EDIT! Autogenerated by HLA tool

class OtherData {
    private id = NUMBER

    static create(
        id: OtherId,
    ): OtherData {
        const instance = new OtherData()
        instance.id = id.getValue()
        return instance
    }

    static createNamed({
        id,
    }: {
        id: OtherId;
    }): OtherData {
        const instance = new OtherData()
        instance.id = id.getValue()
        return instance
    }

    getId(): OtherId {
        return new OtherId(this.id)
    }

    setId(id: OtherId): void {
        this.id = id.getValue()
    }

    update(other: OtherData) {
        this.id = other.id
    }
}