// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.facade.api

val PROFILES_KEY = com.github.bratek20.architecture.properties.api.ListPropertyKey(
    "profiles",
    HlaProfile::class
)