// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.facade.api

import com.github.bratek20.utils.directory.api.*
import com.github.bratek20.hla.generation.api.*

data class ModuleName(
    val value: String
) {
    override fun toString(): String {
        return value.toString()
    }
}

data class ProfileName(
    val value: String
) {
    override fun toString(): String {
        return value.toString()
    }
}

data class ModuleOperationArgs(
    private val hlaFolderPath: String,
    private val profileName: String,
    private val moduleName: String,
) {
    fun getHlaFolderPath(): Path {
        return pathCreate(this.hlaFolderPath)
    }

    fun getProfileName(): ProfileName {
        return ProfileName(this.profileName)
    }

    fun getModuleName(): ModuleName {
        return ModuleName(this.moduleName)
    }

    companion object {
        fun create(
            hlaFolderPath: Path,
            profileName: ProfileName,
            moduleName: ModuleName,
        ): ModuleOperationArgs {
            return ModuleOperationArgs(
                hlaFolderPath = pathGetValue(hlaFolderPath),
                profileName = profileName.value,
                moduleName = moduleName.value,
            )
        }
    }
}

data class AllModulesOperationArgs(
    private val hlaFolderPath: String,
    private val profileName: String,
) {
    fun getHlaFolderPath(): Path {
        return pathCreate(this.hlaFolderPath)
    }

    fun getProfileName(): ProfileName {
        return ProfileName(this.profileName)
    }

    companion object {
        fun create(
            hlaFolderPath: Path,
            profileName: ProfileName,
        ): AllModulesOperationArgs {
            return AllModulesOperationArgs(
                hlaFolderPath = pathGetValue(hlaFolderPath),
                profileName = profileName.value,
            )
        }
    }
}

data class TypeScriptConfig(
    private val mainTsconfigPath: String? = null,
    private val testTsconfigPath: String? = null,
    private val launchJsonPath: String? = null,
    private val packageJsonPath: String? = null,
    private val entryPath: String? = null,
    private val modern: Boolean? = null,
) {
    fun getMainTsconfigPath(): Path? {
        return this.mainTsconfigPath?.let { it -> pathCreate(it) }
    }

    fun getTestTsconfigPath(): Path? {
        return this.testTsconfigPath?.let { it -> pathCreate(it) }
    }

    fun getLaunchJsonPath(): Path? {
        return this.launchJsonPath?.let { it -> pathCreate(it) }
    }

    fun getPackageJsonPath(): Path? {
        return this.packageJsonPath?.let { it -> pathCreate(it) }
    }

    fun getEntryPath(): Path? {
        return this.entryPath?.let { it -> pathCreate(it) }
    }

    fun getModern(): Boolean? {
        return this.modern
    }

    companion object {
        fun create(
            mainTsconfigPath: Path? = null,
            testTsconfigPath: Path? = null,
            launchJsonPath: Path? = null,
            packageJsonPath: Path? = null,
            entryPath: Path? = null,
            modern: Boolean? = null,
        ): TypeScriptConfig {
            return TypeScriptConfig(
                mainTsconfigPath = mainTsconfigPath?.let { it -> pathGetValue(it) },
                testTsconfigPath = testTsconfigPath?.let { it -> pathGetValue(it) },
                launchJsonPath = launchJsonPath?.let { it -> pathGetValue(it) },
                packageJsonPath = packageJsonPath?.let { it -> pathGetValue(it) },
                entryPath = entryPath?.let { it -> pathGetValue(it) },
                modern = modern,
            )
        }
    }
}

data class SubmodulePath(
    private val path: String,
    private val submodule: String? = null,
    private val submodules: List<String> = emptyList(),
) {
    fun getPath(): Path {
        return pathCreate(this.path)
    }

    fun getSubmodule(): SubmoduleName? {
        return this.submodule?.let { it -> SubmoduleName.valueOf(it) }
    }

    fun getSubmodules(): List<SubmoduleName> {
        return this.submodules.map { it -> SubmoduleName.valueOf(it) }
    }

    companion object {
        fun create(
            path: Path,
            submodule: SubmoduleName? = null,
            submodules: List<SubmoduleName> = emptyList(),
        ): SubmodulePath {
            return SubmodulePath(
                path = pathGetValue(path),
                submodule = submodule?.let { it -> it.name },
                submodules = submodules.map { it -> it.name },
            )
        }
    }
}

data class HlaSrcPaths(
    private val default: String,
    private val overrides: List<SubmodulePath> = emptyList(),
) {
    fun getDefault(): Path {
        return pathCreate(this.default)
    }

    fun getOverrides(): List<SubmodulePath> {
        return this.overrides
    }

    companion object {
        fun create(
            default: Path,
            overrides: List<SubmodulePath> = emptyList(),
        ): HlaSrcPaths {
            return HlaSrcPaths(
                default = pathGetValue(default),
                overrides = overrides,
            )
        }
    }
}

data class HlaPaths(
    private val project: String,
    private val src: HlaSrcPaths,
) {
    fun getProject(): Path {
        return pathCreate(this.project)
    }

    fun getSrc(): HlaSrcPaths {
        return this.src
    }

    companion object {
        fun create(
            project: Path,
            src: HlaSrcPaths,
        ): HlaPaths {
            return HlaPaths(
                project = pathGetValue(project),
                src = src,
            )
        }
    }
}

data class HlaProfileImport(
    private val hlaFolderPath: String,
    private val profileName: String,
) {
    fun getHlaFolderPath(): Path {
        return pathCreate(this.hlaFolderPath)
    }

    fun getProfileName(): ProfileName {
        return ProfileName(this.profileName)
    }

    companion object {
        fun create(
            hlaFolderPath: Path,
            profileName: ProfileName,
        ): HlaProfileImport {
            return HlaProfileImport(
                hlaFolderPath = pathGetValue(hlaFolderPath),
                profileName = profileName.value,
            )
        }
    }
}

data class HlaProfile(
    private val name: String,
    private val language: String,
    private val paths: HlaPaths,
    private val typeScript: TypeScriptConfig?,
    private val onlyPatterns: List<String> = emptyList(),
    private val skipPatterns: List<String> = emptyList(),
    private val imports: List<HlaProfileImport> = emptyList(),
) {
    fun getName(): ProfileName {
        return ProfileName(this.name)
    }

    fun getLanguage(): ModuleLanguage {
        return ModuleLanguage.valueOf(this.language)
    }

    fun getPaths(): HlaPaths {
        return this.paths
    }

    fun getTypeScript(): TypeScriptConfig? {
        return this.typeScript
    }

    fun getOnlyPatterns(): List<PatternName> {
        return this.onlyPatterns.map { it -> PatternName.valueOf(it) }
    }

    fun getSkipPatterns(): List<PatternName> {
        return this.skipPatterns.map { it -> PatternName.valueOf(it) }
    }

    fun getImports(): List<HlaProfileImport> {
        return this.imports
    }

    companion object {
        fun create(
            name: ProfileName,
            language: ModuleLanguage,
            paths: HlaPaths,
            typeScript: TypeScriptConfig?,
            onlyPatterns: List<PatternName> = emptyList(),
            skipPatterns: List<PatternName> = emptyList(),
            imports: List<HlaProfileImport> = emptyList(),
        ): HlaProfile {
            return HlaProfile(
                name = name.value,
                language = language.name,
                paths = paths,
                typeScript = typeScript,
                onlyPatterns = onlyPatterns.map { it -> it.name },
                skipPatterns = skipPatterns.map { it -> it.name },
                imports = imports,
            )
        }
    }
}