// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.typesmodule.fixtures

import org.assertj.core.api.Assertions.assertThat

import com.some.pkg.typesmodule.api.*

data class ExpectedDateRange(
    var from: String? = null,
    var to: String? = null,
)
fun assertDateRange(given: DateRange, expectedInit: ExpectedDateRange.() -> Unit) {
    val expected = ExpectedDateRange().apply(expectedInit)

    expected.from?.let {
        assertThat(dateGetValue(dateRangeGetFrom(given))).isEqualTo(it)
    }

    expected.to?.let {
        assertThat(dateGetValue(dateRangeGetTo(given))).isEqualTo(it)
    }
}

data class ExpectedDateRangeProperty(
    var from: String? = null,
    var to: String? = null,
)
fun assertDateRangeProperty(given: DateRangeProperty, expectedInit: ExpectedDateRangeProperty.() -> Unit) {
    val expected = ExpectedDateRangeProperty().apply(expectedInit)

    expected.from?.let {
        assertThat(dateGetValue(given.getFrom())).isEqualTo(it)
    }

    expected.to?.let {
        assertThat(dateGetValue(given.getTo())).isEqualTo(it)
    }
}