// DO NOT EDIT! Autogenerated by HLA tool

namespace OnlyTrackingModule.Impl {
    export class OnlyTrackingDimension extends TrackingDimension {
        constructor(
            some_field: number
        ) {
            super()
            this.some_field = some_field
        }
        private readonly some_field: number
        getTableName(): TrackingTableName {
            return new TrackingTableName("only_tracking_dimension")
        }
    }

    export class OnlyTrackingEvent extends TrackingEvent {
        constructor(
            only_tracking_dimension_id: OnlyTrackingDimension,
            optional_int: Optional<number>
        ) {
            super()
            this.only_tracking_dimension_id = only_tracking_dimension_id
            this.optional_int = optional_int.orElse(undefined)
        }
        private readonly only_tracking_dimension_id: OnlyTrackingDimension
        private readonly optional_int: number
        getTableName(): TrackingTableName {
            return new TrackingTableName("only_tracking_event")
        }
    }
}