// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.someusermodule.web

import com.github.bratek20.architecture.context.api.ContextBuilder
import com.github.bratek20.architecture.context.api.ContextModule
import com.github.bratek20.infrastructure.httpclient.api.HttpClientConfig
import com.github.bratek20.infrastructure.httpserver.api.WebServerModule

import com.some.pkg.someusermodule.api.*
import com.some.pkg.someusermodule.web.*

class SomeUserModuleWebClient(
    private val config: HttpClientConfig
): ContextModule {
    override fun apply(builder: ContextBuilder) {
        builder
            .setImplObject(SomeUserModuleWebClientConfig::class.java, SomeUserModuleWebClientConfig(config))
            .setImpl(SomeUserInterface::class.java, SomeUserInterfaceWebClient::class.java)
    }
}