// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using System.Linq;
using B20.Ext;
using B20.Architecture.Exceptions;

namespace OtherModule.Api {
    public class OtherExtraException: ApiException {
        public OtherExtraException(
            string message = ""
        ): base(message) {
        }
    }
}