// DO NOT EDIT! Autogenerated by HLA tool

import { DateRange } from "./CustomTypes"
import * as CustomTypesMapper from "./CustomTypesMapper"

export class SerializedDateRange {
    private from = STRING
    private to = STRING

    toCustomType(): DateRange {
        return CustomTypesMapper.dateRangeCreate(
            CustomTypesMapper.dateCreate(this.from),
            CustomTypesMapper.dateCreate(this.to),
        )
    }

    static fromCustomType(customType: DateRange): SerializedDateRange {
        const instance = new SerializedDateRange()
        instance.from = CustomTypesMapper.dateGetValue(CustomTypesMapper.dateRangeGetFrom(customType))
        instance.to = CustomTypesMapper.dateGetValue(CustomTypesMapper.dateRangeGetTo(customType))
        return instance
    }
}
