// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using System.Linq;
using B20.Ext;
using UnityEngine;
using ImportingModule.ViewModel;
using OtherModule.View;

namespace ImportingModule.View {
    public class ImportingVmView: ElementView<ImportingVm> {
        [SerializeField]
        OtherClassView other;
        protected override void OnBind() {
            base.OnBind();
            other.Bind(ViewModel.Other);
        }
    }
}