// DO NOT EDIT! Autogenerated by HLA tool

import { SomeUserModuleWebClientConfig } from "./WebCommon"

export const config = new SomeUserModuleWebClientConfig(
    HttpClientConfig.create(
        EnvVars.Api.Get(new VariableName($baseUrl)),
        $serverName,
        Optional.of(HttpClientAuth.create(EnvVars.Api.Get(new VariableName($auth))))
    )
)

export function someMethod(c: HandlerContext): void {
    new Web.SomeUserInterfaceWebClient(Web.config, c).someMethod()
}
