// DO NOT EDIT! Autogenerated by HLA tool

namespace SomeUserModule.Web {
    export const config = new SomeUserModuleWebClientConfig(
        HttpClientConfig.create(
            EnvVars.Api.Get(new VariableName($baseUrl)),
            $serverName,
            Optional.of(HttpClientAuth.create(EnvVars.Api.Get(new VariableName($auth))))
        )
    )
}

namespace SomeUserModule.Api {
    export function someMethod(c: HandlerContext): void {
        new Web.SomeUserInterfaceWebClient(Web.config, c).someMethod()
    }
}