// DO NOT EDIT! Autogenerated by HLA tool

namespace SomeUserModule.Web {
    export class SomeUserInterfaceWebClient implements SomeUserInterface {
        constructor(
            config: SomeUserModuleWebClientConfig,
            c: HandlerContext
        ) {
            this.client = HttpClient.Api.create(config.value, c)
        }
        private readonly client: HttpClient
        someMethod(): void {
            this.client.post("/someUserInterface/someMethod", Optional.empty())
        }
    }
}