// DO NOT EDIT! Autogenerated by HLA tool

import { NoInterfaceId } from "../../../main/NoInterfacesModule/Api/ValueObjects"
import { diffNoInterfaceId } from "./Diffs"

export function noInterfaceId(given: NoInterfaceId, expected: string) {
    const diff = diffNoInterfaceId(given, expected)
    AssertEquals(diff, "", diff)
}
