// DO NOT EDIT! Autogenerated by HLA tool

namespace NoInterfacesModule {
    export function diffNoInterfaceId(given: NoInterfaceId, expected: string, path: string = ""): string {
        if (given.getValue() != expected) { return `${path}value ${given.getValue()} != ${expected}` }
        return ""
    }
}