// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.hlatypesworld.fixtures

import org.assertj.core.api.Assertions.assertThat

import com.github.bratek20.hla.hlatypesworld.api.*

fun assertHlaTypePath(given: HlaTypePath, expected: String) {
    val diff = diffHlaTypePath(given, expected)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}
