// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.hlatypesworld.fixtures

import com.github.bratek20.hla.hlatypesworld.api.*

fun hlaTypePath(value: String = "SomeRootGroup/SomeNestedGroup/SomeModule/Api/ValueObjects"): HlaTypePath {
    return hlaTypePathCreate(value)
}
