// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.type.api

data class HlaType(
    private val name: String,
    private val path: String,
) {
    fun getName(): String {
        return this.name
    }

    fun getPath(): HlaTypePath {
        return hlaTypePathCreate(this.path)
    }

    companion object {
        fun create(
            name: String,
            path: HlaTypePath,
        ): HlaType {
            return HlaType(
                name = name,
                path = hlaTypePathGetValue(path),
            )
        }
    }
}