// DO NOT EDIT! Autogenerated by HLA tool

import { MockArg } from "../../../main/ModuleOnlyForMocksArgs/Api/ValueObjects"
import { OtherId } from "../../../main/OtherModule/Api/ValueObjects"
import { DateRangeWrapper } from "../../../main/SomeModule/Api/CustomTypes"
import * as CustomTypesMapper from "../../../main/SomeModule/Api/CustomTypesMapper"
import { SomeData, SomeData2 } from "../../../main/SomeModule/Api/DataClasses"
import { SomeEnum, SomeEnum2 } from "../../../main/SomeModule/Api/Enums"
import { SomeEvent } from "../../../main/SomeModule/Api/Notifications"
import { ClassExtendingOtherClass, ClassExtendingSomeClass, ClassHavingOptList, ClassHavingOptSimpleVo, ClassWithBoolField, ClassWithComplexMap, ClassWithEnumList, ClassWithOptExamples, ClassWithOptionalMap, ClassWithSimpleMap, ClassWithVoMap, ComplexStructureWithNestedUniqueIds, CustomTypesProperty, CustomTypesPropertyOptionalList, NestedClassLevel1, NestedClassLevel2, NestedUniqueIds, NestedValue, OptionalFieldProperty, RecordClass, RecursiveClass, SelfReferencingProperty, SomeClass, SomeClass2, SomeClass3, SomeClass4, SomeClass5, SomeClass6, SomeClassWIthOtherClassUniqueIds, SomeHandlerInput, SomeHandlerOutput, SomeId, SomeId2, SomeIntWrapper, SomeInterfaceSomeCommandArgs, SomeInterfaceToTestMockArgsImportSomeMethodArgs, SomeOtherId, SomeProperty, SomeProperty2, SomePropertyEntry, SomeQueryInput, SomeReferencingProperty, SomeReferencingPropertyFieldList, SomeRenamedReferencingProperty, SomeRenamedReferencingRenamedProperty, SomeRenamedSourcePropertyEntry, SomeStructWithNestedOtherClassUniqueIds, SomeStructureWithMultipleUniqueNestedIds, SomeStructureWithUniqueIds, SomeStructureWithUniqueNestedIds } from "../../../main/SomeModule/Api/ValueObjects"
import * as TypesModuleCustomTypesMapper from "../../../main/TypesModule/Api/CustomTypesMapper"
import * as OtherModuleBuilder from "../../OtherModule/Fixtures/Builders"
import * as SimpleModuleBuilder from "../../SimpleModule/Fixtures/Builders"
import * as SomeUserModuleBuilder from "../../SomeUserModule/Fixtures/Builders"
import * as TypesModuleBuilder from "../../TypesModule/Fixtures/Builders"

export function someId(value: string = "someValue"): SomeId {
    return new SomeId(value)
}

export function someOtherId(value: string = "someValue"): SomeOtherId {
    return new SomeOtherId(value)
}

export function someIntWrapper(value: number = 5): SomeIntWrapper {
    return new SomeIntWrapper(value)
}

export function someId2(value: number = 0): SomeId2 {
    return new SomeId2(value)
}

export interface SomeClassDef {
    id?: string,
    amount?: number,
}
export function someClass(def?: SomeClassDef): SomeClass {
    const final_id = def?.id ?? "someValue"
    const final_amount = def?.amount ?? 10

    return SomeClass.create(
        new SomeId(final_id),
        final_amount,
    )
}

export interface SomeClass2Def {
    id?: string,
    names?: string[],
    ids?: string[],
    enabled?: boolean,
}
export function someClass2(def?: SomeClass2Def): SomeClass2 {
    const final_id = def?.id ?? "someValue"
    const final_names = def?.names ?? []
    const final_ids = def?.ids ?? []
    const final_enabled = def?.enabled ?? true

    return SomeClass2.create(
        new SomeId(final_id),
        final_names,
        final_ids.map(it => new SomeId(it)),
        final_enabled,
    )
}

export interface SomeClass3Def {
    class2Object?: Builder.SomeClass2Def,
    someEnum?: string,
    class2List?: Builder.SomeClass2Def[],
}
export function someClass3(def?: SomeClass3Def): SomeClass3 {
    const final_class2Object = def?.class2Object ?? {}
    const final_someEnum = def?.someEnum ?? SomeEnum.VALUE_A.getName()
    const final_class2List = def?.class2List ?? []

    return SomeClass3.create(
        Builder.someClass2(final_class2Object),
        SomeEnum.fromName(final_someEnum),
        final_class2List.map(it => Builder.someClass2(it)),
    )
}

export interface SomeClass4Def {
    otherId?: number,
    otherClass?: OtherModuleBuilder.OtherClassDef,
    otherIdList?: number[],
    otherClassList?: OtherModuleBuilder.OtherClassDef[],
}
export function someClass4(def?: SomeClass4Def): SomeClass4 {
    const final_otherId = def?.otherId ?? 0
    const final_otherClass = def?.otherClass ?? {}
    const final_otherIdList = def?.otherIdList ?? []
    const final_otherClassList = def?.otherClassList ?? []

    return SomeClass4.create(
        new OtherId(final_otherId),
        OtherModuleBuilder.otherClass(final_otherClass),
        final_otherIdList.map(it => new OtherId(it)),
        final_otherClassList.map(it => OtherModuleBuilder.otherClass(it)),
    )
}

export interface SomeClass5Def {
    date?: string,
    dateRange?: TypesModuleBuilder.DateRangeDef,
    dateRangeWrapper?: Builder.DateRangeWrapperDef,
    someProperty?: Builder.SomePropertyDef,
    otherProperty?: OtherModuleBuilder.OtherPropertyDef,
}
export function someClass5(def?: SomeClass5Def): SomeClass5 {
    const final_date = def?.date ?? "01/01/1970 00:00"
    const final_dateRange = def?.dateRange ?? {}
    const final_dateRangeWrapper = def?.dateRangeWrapper ?? {}
    const final_someProperty = def?.someProperty ?? {}
    const final_otherProperty = def?.otherProperty ?? {}

    return SomeClass5.create(
        TypesModuleCustomTypesMapper.dateCreate(final_date),
        TypesModuleBuilder.dateRange(final_dateRange),
        Builder.dateRangeWrapper(final_dateRangeWrapper),
        Builder.someProperty(final_someProperty),
        OtherModuleBuilder.otherProperty(final_otherProperty),
    )
}

export interface SomeClass6Def {
    someClassOpt?: Builder.SomeClassDef,
    optString?: string,
    class2List?: Builder.SomeClass2Def[],
    sameClassList?: Builder.SomeClass6Def[],
}
export function someClass6(def?: SomeClass6Def): SomeClass6 {
    const final_someClassOpt = def?.someClassOpt ?? undefined
    const final_optString = def?.optString ?? undefined
    const final_class2List = def?.class2List ?? []
    const final_sameClassList = def?.sameClassList ?? []

    return SomeClass6.create(
        Optional.of(final_someClassOpt).map(it => Builder.someClass(it)),
        Optional.of(final_optString),
        final_class2List.map(it => Builder.someClass2(it)),
        final_sameClassList.map(it => Builder.someClass6(it)),
    )
}

export interface ClassHavingOptListDef {
    optList?: Builder.SomeClassDef[],
}
export function classHavingOptList(def?: ClassHavingOptListDef): ClassHavingOptList {
    const final_optList = def?.optList ?? undefined

    return ClassHavingOptList.create(
        Optional.of(final_optList).map(it => it.map(it => Builder.someClass(it))),
    )
}

export interface ClassHavingOptSimpleVoDef {
    optSimpleVo?: string,
}
export function classHavingOptSimpleVo(def?: ClassHavingOptSimpleVoDef): ClassHavingOptSimpleVo {
    const final_optSimpleVo = def?.optSimpleVo ?? undefined

    return ClassHavingOptSimpleVo.create(
        Optional.of(final_optSimpleVo).map(it => new SomeId(it)),
    )
}

export interface RecordClassDef {
    id?: string,
    amount?: number,
}
export function recordClass(def?: RecordClassDef): RecordClass {
    const final_id = def?.id ?? "someValue"
    const final_amount = def?.amount ?? 0

    return RecordClass.create(
        new SomeId(final_id),
        final_amount,
    )
}

export interface ClassWithOptExamplesDef {
    optInt?: number,
    optIntWrapper?: number,
}
export function classWithOptExamples(def?: ClassWithOptExamplesDef): ClassWithOptExamples {
    const final_optInt = def?.optInt ?? 1
    const final_optIntWrapper = def?.optIntWrapper ?? 2

    return ClassWithOptExamples.create(
        Optional.of(final_optInt),
        Optional.of(final_optIntWrapper).map(it => new SomeIntWrapper(it)),
    )
}

export interface ClassWithEnumListDef {
    enumList?: string[],
}
export function classWithEnumList(def?: ClassWithEnumListDef): ClassWithEnumList {
    const final_enumList = def?.enumList ?? []

    return ClassWithEnumList.create(
        final_enumList.map(it => SomeEnum2.fromName(it)),
    )
}

export interface ClassWithBoolFieldDef {
    boolField?: boolean,
}
export function classWithBoolField(def?: ClassWithBoolFieldDef): ClassWithBoolField {
    const final_boolField = def?.boolField ?? false

    return ClassWithBoolField.create(
        final_boolField,
    )
}

export interface RecursiveClassDef {
    meList?: Builder.RecursiveClassDef[],
    meOpt?: Builder.RecursiveClassDef,
    meOptList?: Builder.RecursiveClassDef[],
}
export function recursiveClass(def?: RecursiveClassDef): RecursiveClass {
    const final_meList = def?.meList ?? []
    const final_meOpt = def?.meOpt ?? undefined
    const final_meOptList = def?.meOptList ?? undefined

    return RecursiveClass.create(
        final_meList.map(it => Builder.recursiveClass(it)),
        Optional.of(final_meOpt).map(it => Builder.recursiveClass(it)),
        Optional.of(final_meOptList).map(it => it.map(it => Builder.recursiveClass(it))),
    )
}

export interface ClassWithSimpleMapDef {
    primitiveMap?: Map<string, number>,
}
export function classWithSimpleMap(def?: ClassWithSimpleMapDef): ClassWithSimpleMap {
    const final_primitiveMap = def?.primitiveMap ?? new Map()

    return ClassWithSimpleMap.create(
        final_primitiveMap,
    )
}

export interface ClassWithVoMapDef {
    idMap?: Map<string, string>,
}
export function classWithVoMap(def?: ClassWithVoMapDef): ClassWithVoMap {
    const final_idMap = def?.idMap ?? new Map()

    return ClassWithVoMap.create(
        new Map(),
    )
}

export interface ClassWithOptionalMapDef {
    optMap?: Map<string, number>,
}
export function classWithOptionalMap(def?: ClassWithOptionalMapDef): ClassWithOptionalMap {
    const final_optMap = def?.optMap ?? undefined

    return ClassWithOptionalMap.create(
        Optional.of(final_optMap),
    )
}

export interface ClassWithComplexMapDef {
    complexMap?: Map<string, SomeUserModuleBuilder.SomeUserValueObjectDef>,
}
export function classWithComplexMap(def?: ClassWithComplexMapDef): ClassWithComplexMap {
    const final_complexMap = def?.complexMap ?? new Map()

    return ClassWithComplexMap.create(
        new Map(),
    )
}

export interface ClassExtendingSomeClassDef {
    id?: string,
    amount?: number,
    extraField?: string,
}
export function classExtendingSomeClass(def?: ClassExtendingSomeClassDef): ClassExtendingSomeClass {
    const final_id = def?.id ?? "someValue"
    const final_amount = def?.amount ?? 10
    const final_extraField = def?.extraField ?? "someValue"

    return ClassExtendingSomeClass.create(
        new SomeId(final_id),
        final_amount,
        final_extraField,
    )
}

export interface ClassExtendingOtherClassDef {
    id?: number,
    amount?: number,
    extraField?: string,
}
export function classExtendingOtherClass(def?: ClassExtendingOtherClassDef): ClassExtendingOtherClass {
    const final_id = def?.id ?? 0
    const final_amount = def?.amount ?? 0
    const final_extraField = def?.extraField ?? "someValue"

    return ClassExtendingOtherClass.create(
        new OtherId(final_id),
        final_amount,
        final_extraField,
    )
}

export interface SomeQueryInputDef {
    id?: string,
    amount?: number,
}
export function someQueryInput(def?: SomeQueryInputDef): SomeQueryInput {
    const final_id = def?.id ?? "someValue"
    const final_amount = def?.amount ?? 0

    return SomeQueryInput.create(
        new SomeId(final_id),
        final_amount,
    )
}

export interface SomeHandlerInputDef {
    id?: string,
    amount?: number,
}
export function someHandlerInput(def?: SomeHandlerInputDef): SomeHandlerInput {
    const final_id = def?.id ?? "someValue"
    const final_amount = def?.amount ?? 0

    return SomeHandlerInput.create(
        new SomeId(final_id),
        final_amount,
    )
}

export interface SomeHandlerOutputDef {
    id?: string,
    amount?: number,
}
export function someHandlerOutput(def?: SomeHandlerOutputDef): SomeHandlerOutput {
    const final_id = def?.id ?? "someValue"
    const final_amount = def?.amount ?? 0

    return SomeHandlerOutput.create(
        new SomeId(final_id),
        final_amount,
    )
}

export interface SomePropertyDef {
    other?: OtherModuleBuilder.OtherPropertyDef,
    id2?: number,
    range?: TypesModuleBuilder.DateRangeDef,
    doubleExample?: number,
    longExample?: number,
    goodName?: string,
    customData?: any,
    as?: string,
}
export function someProperty(def?: SomePropertyDef): SomeProperty {
    const final_other = def?.other ?? {}
    const final_id2 = def?.id2 ?? undefined
    const final_range = def?.range ?? undefined
    const final_doubleExample = def?.doubleExample ?? 0
    const final_longExample = def?.longExample ?? 0
    const final_goodName = def?.goodName ?? "someValue"
    const final_customData = def?.customData ?? {}
    const final_as = def?.as ?? "someValue"

    return SomeProperty.create(
        OtherModuleBuilder.otherProperty(final_other),
        Optional.of(final_id2).map(it => new SomeId2(it)),
        Optional.of(final_range).map(it => TypesModuleBuilder.dateRange(it)),
        final_doubleExample,
        final_longExample,
        final_goodName,
        final_customData,
        final_as,
    )
}

export interface SomeProperty2Def {
    value?: string,
    custom?: any,
    someEnum?: string,
    customOpt?: any,
    kotlinKeyword?: string,
}
export function someProperty2(def?: SomeProperty2Def): SomeProperty2 {
    const final_value = def?.value ?? "someValue"
    const final_custom = def?.custom ?? {}
    const final_someEnum = def?.someEnum ?? SomeEnum.VALUE_A.getName()
    const final_customOpt = def?.customOpt ?? undefined
    const final_kotlinKeyword = def?.kotlinKeyword ?? "someValue"

    return SomeProperty2.create(
        final_value,
        final_custom,
        SomeEnum.fromName(final_someEnum),
        Optional.of(final_customOpt),
        final_kotlinKeyword,
    )
}

export interface SomePropertyEntryDef {
    id?: string,
    exampleInt?: number,
    exampleLong?: number,
    exampleDouble?: number,
    exampleBool?: boolean,
    exampleString?: string,
    exampleNumericCustomType?: number,
    exampleNumericCustomType2?: number,
    exampleVONumeric?: number,
    exampleVONumeric2?: number,
}
export function somePropertyEntry(def?: SomePropertyEntryDef): SomePropertyEntry {
    const final_id = def?.id ?? "someValue"
    const final_exampleInt = def?.exampleInt ?? 1
    const final_exampleLong = def?.exampleLong ?? 2
    const final_exampleDouble = def?.exampleDouble ?? 3.0
    const final_exampleBool = def?.exampleBool ?? true
    const final_exampleString = def?.exampleString ?? "ABC"
    const final_exampleNumericCustomType = def?.exampleNumericCustomType ?? 1
    const final_exampleNumericCustomType2 = def?.exampleNumericCustomType2 ?? 2
    const final_exampleVONumeric = def?.exampleVONumeric ?? 5
    const final_exampleVONumeric2 = def?.exampleVONumeric2 ?? 3

    return SomePropertyEntry.create(
        new SomeId(final_id),
        final_exampleInt,
        final_exampleLong,
        final_exampleDouble,
        final_exampleBool,
        final_exampleString,
        TypesModuleCustomTypesMapper.tierCreate(final_exampleNumericCustomType),
        TypesModuleCustomTypesMapper.tierCreate(final_exampleNumericCustomType2),
        new SomeIntWrapper(final_exampleVONumeric),
        new SomeIntWrapper(final_exampleVONumeric2),
    )
}

export interface SomeRenamedSourcePropertyEntryDef {
    id?: string,
}
export function someRenamedSourcePropertyEntry(def?: SomeRenamedSourcePropertyEntryDef): SomeRenamedSourcePropertyEntry {
    const final_id = def?.id ?? "someValue"

    return SomeRenamedSourcePropertyEntry.create(
        new SomeOtherId(final_id),
    )
}

export interface SomeReferencingPropertyDef {
    referenceId?: string,
}
export function someReferencingProperty(def?: SomeReferencingPropertyDef): SomeReferencingProperty {
    const final_referenceId = def?.referenceId ?? "someValue"

    return SomeReferencingProperty.create(
        new SomeId(final_referenceId),
    )
}

export interface SomeRenamedReferencingPropertyDef {
    referenceId?: string,
}
export function someRenamedReferencingProperty(def?: SomeRenamedReferencingPropertyDef): SomeRenamedReferencingProperty {
    const final_referenceId = def?.referenceId ?? "someValue"

    return SomeRenamedReferencingProperty.create(
        new SomeId(final_referenceId),
    )
}

export interface SomeRenamedReferencingRenamedPropertyDef {
    referenceId?: string,
}
export function someRenamedReferencingRenamedProperty(def?: SomeRenamedReferencingRenamedPropertyDef): SomeRenamedReferencingRenamedProperty {
    const final_referenceId = def?.referenceId ?? "someValue"

    return SomeRenamedReferencingRenamedProperty.create(
        new SomeOtherId(final_referenceId),
    )
}

export interface SomeReferencingPropertyFieldListDef {
    referenceIdList?: string[],
}
export function someReferencingPropertyFieldList(def?: SomeReferencingPropertyFieldListDef): SomeReferencingPropertyFieldList {
    const final_referenceIdList = def?.referenceIdList ?? []

    return SomeReferencingPropertyFieldList.create(
        final_referenceIdList.map(it => new SomeId(it)),
    )
}

export interface SomeStructureWithUniqueIdsDef {
    entries?: SimpleModuleBuilder.UniqueIdEntryDef[],
}
export function someStructureWithUniqueIds(def?: SomeStructureWithUniqueIdsDef): SomeStructureWithUniqueIds {
    const final_entries = def?.entries ?? []

    return SomeStructureWithUniqueIds.create(
        final_entries.map(it => SimpleModuleBuilder.uniqueIdEntry(it)),
    )
}

export interface NestedUniqueIdsDef {
    entries?: SimpleModuleBuilder.UniqueIdEntryDef[],
}
export function nestedUniqueIds(def?: NestedUniqueIdsDef): NestedUniqueIds {
    const final_entries = def?.entries ?? []

    return NestedUniqueIds.create(
        final_entries.map(it => SimpleModuleBuilder.uniqueIdEntry(it)),
    )
}

export interface SomeStructureWithUniqueNestedIdsDef {
    nestedUniqueIds?: Builder.NestedUniqueIdsDef[],
}
export function someStructureWithUniqueNestedIds(def?: SomeStructureWithUniqueNestedIdsDef): SomeStructureWithUniqueNestedIds {
    const final_nestedUniqueIds = def?.nestedUniqueIds ?? []

    return SomeStructureWithUniqueNestedIds.create(
        final_nestedUniqueIds.map(it => Builder.nestedUniqueIds(it)),
    )
}

export interface SomeStructureWithMultipleUniqueNestedIdsDef {
    moreNestedFields?: Builder.SomeStructureWithUniqueNestedIdsDef[],
}
export function someStructureWithMultipleUniqueNestedIds(def?: SomeStructureWithMultipleUniqueNestedIdsDef): SomeStructureWithMultipleUniqueNestedIds {
    const final_moreNestedFields = def?.moreNestedFields ?? []

    return SomeStructureWithMultipleUniqueNestedIds.create(
        final_moreNestedFields.map(it => Builder.someStructureWithUniqueNestedIds(it)),
    )
}

export interface SomeClassWIthOtherClassUniqueIdsDef {
    otherClass?: OtherModuleBuilder.OtherClassWIthUniqueIdDef,
}
export function someClassWIthOtherClassUniqueIds(def?: SomeClassWIthOtherClassUniqueIdsDef): SomeClassWIthOtherClassUniqueIds {
    const final_otherClass = def?.otherClass ?? {}

    return SomeClassWIthOtherClassUniqueIds.create(
        OtherModuleBuilder.otherClassWIthUniqueId(final_otherClass),
    )
}

export interface SomeStructWithNestedOtherClassUniqueIdsDef {
    someNestedWithUniqueIds?: Builder.SomeClassWIthOtherClassUniqueIdsDef[],
}
export function someStructWithNestedOtherClassUniqueIds(def?: SomeStructWithNestedOtherClassUniqueIdsDef): SomeStructWithNestedOtherClassUniqueIds {
    const final_someNestedWithUniqueIds = def?.someNestedWithUniqueIds ?? []

    return SomeStructWithNestedOtherClassUniqueIds.create(
        final_someNestedWithUniqueIds.map(it => Builder.someClassWIthOtherClassUniqueIds(it)),
    )
}

export interface NestedClassLevel2Def {
    uniqueIds?: OtherModuleBuilder.OtherClassWIthUniqueIdDef[],
}
export function nestedClassLevel2(def?: NestedClassLevel2Def): NestedClassLevel2 {
    const final_uniqueIds = def?.uniqueIds ?? []

    return NestedClassLevel2.create(
        final_uniqueIds.map(it => OtherModuleBuilder.otherClassWIthUniqueId(it)),
    )
}

export interface NestedClassLevel1Def {
    nestLevel2?: Builder.NestedClassLevel2Def[],
}
export function nestedClassLevel1(def?: NestedClassLevel1Def): NestedClassLevel1 {
    const final_nestLevel2 = def?.nestLevel2 ?? []

    return NestedClassLevel1.create(
        final_nestLevel2.map(it => Builder.nestedClassLevel2(it)),
    )
}

export interface ComplexStructureWithNestedUniqueIdsDef {
    id?: string,
    nestLevel1?: Builder.NestedClassLevel1Def[],
}
export function complexStructureWithNestedUniqueIds(def?: ComplexStructureWithNestedUniqueIdsDef): ComplexStructureWithNestedUniqueIds {
    const final_id = def?.id ?? "someValue"
    const final_nestLevel1 = def?.nestLevel1 ?? []

    return ComplexStructureWithNestedUniqueIds.create(
        final_id,
        final_nestLevel1.map(it => Builder.nestedClassLevel1(it)),
    )
}

export interface NestedValueDef {
    value?: string,
}
export function nestedValue(def?: NestedValueDef): NestedValue {
    const final_value = def?.value ?? "someValue"

    return NestedValue.create(
        final_value,
    )
}

export interface OptionalFieldPropertyDef {
    optionalField?: Builder.NestedValueDef,
}
export function optionalFieldProperty(def?: OptionalFieldPropertyDef): OptionalFieldProperty {
    const final_optionalField = def?.optionalField ?? undefined

    return OptionalFieldProperty.create(
        Optional.of(final_optionalField).map(it => Builder.nestedValue(it)),
    )
}

export interface CustomTypesPropertyDef {
    date?: string,
    dateRange?: TypesModuleBuilder.DateRangeDef,
}
export function customTypesProperty(def?: CustomTypesPropertyDef): CustomTypesProperty {
    const final_date = def?.date ?? "01/01/1970 00:00"
    const final_dateRange = def?.dateRange ?? {}

    return CustomTypesProperty.create(
        TypesModuleCustomTypesMapper.dateCreate(final_date),
        TypesModuleBuilder.dateRange(final_dateRange),
    )
}

export interface SelfReferencingPropertyDef {
    optionalSelf?: Builder.SelfReferencingPropertyDef,
    listSelf?: Builder.SelfReferencingPropertyDef[],
    optionalListSelf?: Builder.SelfReferencingPropertyDef[],
}
export function selfReferencingProperty(def?: SelfReferencingPropertyDef): SelfReferencingProperty {
    const final_optionalSelf = def?.optionalSelf ?? undefined
    const final_listSelf = def?.listSelf ?? []
    const final_optionalListSelf = def?.optionalListSelf ?? undefined

    return SelfReferencingProperty.create(
        Optional.of(final_optionalSelf).map(it => Builder.selfReferencingProperty(it)),
        final_listSelf.map(it => Builder.selfReferencingProperty(it)),
        Optional.of(final_optionalListSelf).map(it => it.map(it => Builder.selfReferencingProperty(it))),
    )
}

export interface CustomTypesPropertyOptionalListDef {
    id?: string,
    customPropertiesList?: Builder.CustomTypesPropertyDef[],
}
export function customTypesPropertyOptionalList(def?: CustomTypesPropertyOptionalListDef): CustomTypesPropertyOptionalList {
    const final_id = def?.id ?? "someValue"
    const final_customPropertiesList = def?.customPropertiesList ?? undefined

    return CustomTypesPropertyOptionalList.create(
        final_id,
        Optional.of(final_customPropertiesList).map(it => it.map(it => Builder.customTypesProperty(it))),
    )
}

export interface SomeInterfaceSomeCommandArgsDef {
    id?: string,
    amount?: number,
}
export function someInterfaceSomeCommandArgs(def?: SomeInterfaceSomeCommandArgsDef): SomeInterfaceSomeCommandArgs {
    const final_id = def?.id ?? "someValue"
    const final_amount = def?.amount ?? 0

    return SomeInterfaceSomeCommandArgs.create(
        new SomeId(final_id),
        final_amount,
    )
}

export interface SomeInterfaceToTestMockArgsImportSomeMethodArgsDef {
    arg1?: string,
    arg2?: string,
}
export function someInterfaceToTestMockArgsImportSomeMethodArgs(def?: SomeInterfaceToTestMockArgsImportSomeMethodArgsDef): SomeInterfaceToTestMockArgsImportSomeMethodArgs {
    const final_arg1 = def?.arg1 ?? "someValue"
    const final_arg2 = def?.arg2 ?? "someValue"

    return SomeInterfaceToTestMockArgsImportSomeMethodArgs.create(
        new MockArg(final_arg1),
        new MockArg(final_arg2),
    )
}

export interface DateRangeWrapperDef {
    range?: TypesModuleBuilder.DateRangeDef,
}
export function dateRangeWrapper(def?: DateRangeWrapperDef): DateRangeWrapper {
    const final_range = def?.range ?? {}

    return CustomTypesMapper.dateRangeWrapperCreate(
        TypesModuleBuilder.dateRange(final_range),
    )
}

export interface SomeDataDef {
    id?: string,
    other?: OtherModuleBuilder.OtherDataDef,
    custom?: any,
    customOpt?: any,
    goodDataName?: string,
    someDefault?: string,
}
export function someData(def?: SomeDataDef): SomeData {
    const final_id = def?.id ?? "someValue"
    const final_other = def?.other ?? {}
    const final_custom = def?.custom ?? {}
    const final_customOpt = def?.customOpt ?? undefined
    const final_goodDataName = def?.goodDataName ?? "someValue"
    const final_someDefault = def?.someDefault ?? "defaultValue"

    return SomeData.create(
        new SomeId(final_id),
        OtherModuleBuilder.otherData(final_other),
        final_custom,
        Optional.of(final_customOpt),
        final_goodDataName,
        new SomeOtherId(final_someDefault),
    )
}

export interface SomeData2Def {
    optEnum?: string,
    optCustomType?: string,
}
export function someData2(def?: SomeData2Def): SomeData2 {
    const final_optEnum = def?.optEnum ?? undefined
    const final_optCustomType = def?.optCustomType ?? undefined

    return SomeData2.create(
        Optional.of(final_optEnum).map(it => SomeEnum.fromName(it)),
        Optional.of(final_optCustomType).map(it => TypesModuleCustomTypesMapper.dateCreate(it)),
    )
}

export interface SomeEventDef {
    someField?: string,
    otherClass?: OtherModuleBuilder.OtherClassDef,
    optField?: string,
}
export function someEvent(def?: SomeEventDef): SomeEvent {
    const final_someField = def?.someField ?? "someValue"
    const final_otherClass = def?.otherClass ?? {}
    const final_optField = def?.optField ?? undefined

    return SomeEvent.create(
        final_someField,
        OtherModuleBuilder.otherClass(final_otherClass),
        Optional.of(final_optField),
    )
}
