// DO NOT EDIT! Autogenerated by HLA tool

namespace OtherModule.Web {
    Handlers.Api.RegisterModuleHandlers(DependencyName.OtherModule, ["OtherModule.otherHandler", otherHandler])

    export function otherHandler(rawRequest: any, c: HandlerContext): IOpResult {
        Api.otherHandler(c)
        return Utils.OK({})
    }
}