// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using System.Linq;
using B20.Ext;
using HttpClientModule.Api;
using SomeUserModule.Api;

namespace SomeUserModule.Web {
    public class SomeUserModuleWebClientConfig {
        public HttpClientConfig Value { get; }

        public SomeUserModuleWebClientConfig(
            HttpClientConfig value
        ) {
            Value = value;
        }
    }
}