// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using System.Linq;
using B20.Ext;
using B20.Architecture.Contexts.Api;
using HttpClientModule.Api;
using SomeUserModule.Api;

namespace SomeUserModule.Web {
    public class SomeUserModuleWebClient: ContextModule {
        readonly HttpClientConfig config;

        public SomeUserModuleWebClient(
            HttpClientConfig config
        ) {
            this.config = config;
        }
        public void Apply(ContextBuilder builder) {
            builder
                .SetImplObject<SomeUserModuleWebClientConfig>(new SomeUserModuleWebClientConfig(config))
                .SetImpl<SomeUserInterface, SomeUserInterfaceWebClient>();
        }
    }
}