// some comment
Enums
    SomeEnum
        VALUE_A
        VALUE_B

ValueObjects
    SomeId: string
    SomeClass
        id: SomeId
        amount: int (public)

    SomeClass2
        id: SomeId
        names: string[]
        ids: SomeId[]
        enabled: bool = true

    SomeClass3
        class2Object: SomeClass2
        class2List: SomeClass2[]

    SomeClass4
        otherId: OtherId
        otherClass: OtherClass
        otherIdList: OtherId[]
        otherClassList: OtherClass[]

    SomeClass5
        otherId: OtherId?
        optOtherIds: OtherId[]?

Exceptions
    SomeExtraException

Events
    SomeEvent
        someField: string

Interfaces
    SomeInterface
        someCommand(id: SomeId, amount: int)
            throws
                SomeException
                SomeException2
        someQuery(id: SomeId): SomeClass
        noArgQuery(): SomeClass
        someOptionalQuery(id: SomeId?): SomeClass?