// DO NOT EDIT! Autogenerated by HLA tool

namespace ImportingModule.Builder {
    export interface ImportingPropertyDef {
        other?: OtherModule.Builder.OtherPropertyDef,
    }
    export function importingProperty(def?: ImportingPropertyDef): ImportingProperty {
        const other = def?.other ?? {}

        return ImportingProperty.create(
            OtherModule.Builder.otherProperty(other),
        )
    }
}