// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.othermodule.api

interface OtherInterface {
    fun otherMethod(): Unit
}

interface OtherModuleHandlers {
    fun otherHandler(i: OtherHandlerInput): OtherHandlerOutput
}