// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using System.Linq;
using B20.Ext;
using OtherModule.Api;
using TypesModule.Api;

namespace SomeModule.Api {
    public class SomeEvent: ValueObject {
        readonly string someField;
        readonly OtherClass otherClass;

        public SomeEvent(
            string someField,
            OtherClass otherClass
        ) {
            this.someField = someField;
            this.otherClass = otherClass;
        }
        public string GetSomeField() {
            return someField;
        }
        public OtherClass GetOtherClass() {
            return otherClass;
        }
        public static SomeEvent Create(string someField, OtherClass otherClass) {
            return new SomeEvent(someField, otherClass);
        }
    }
}