// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.hla.tracking.fixtures

import org.assertj.core.api.Assertions.assertThat

import com.github.bratek20.hla.definitions.api.*
import com.github.bratek20.hla.definitions.fixtures.*

import com.github.bratek20.hla.tracking.api.*

fun assertTableDefinition(given: TableDefinition, expectedInit: ExpectedTableDefinition.() -> Unit) {
    val diff = diffTableDefinition(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertTrackingSubmoduleDefinition(given: TrackingSubmoduleDefinition, expectedInit: ExpectedTrackingSubmoduleDefinition.() -> Unit) {
    val diff = diffTrackingSubmoduleDefinition(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}