// DO NOT EDIT! Autogenerated by HLA tool

package pl.bratek20.hla.generation.fixtures

import org.assertj.core.api.Assertions.assertThat

import pl.bratek20.hla.definitions.api.*
import pl.bratek20.hla.definitions.fixtures.*
import pl.bratek20.hla.directory.api.*
import pl.bratek20.hla.directory.fixtures.*
import pl.bratek20.hla.facade.api.*
import pl.bratek20.hla.facade.fixtures.*

import pl.bratek20.hla.generation.api.*

fun assertGenerateArgs(given: GenerateArgs, expectedInit: ExpectedGenerateArgs.() -> Unit) {
    val diff = diffGenerateArgs(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertGenerateResult(given: GenerateResult, expectedInit: ExpectedGenerateResult.() -> Unit) {
    val diff = diffGenerateResult(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}