// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.somemodule.api

import com.some.pkg.othermodule.api.*
import com.some.pkg.simplemodule.api.*
import com.some.pkg.typesmodule.api.*

val SOME_KEY_DATA_KEY = com.github.bratek20.architecture.data.api.ObjectDataKey(
    "SomeKey",
    SomeData::class
)