// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.somemodule.api

import com.some.pkg.othermodule.api.*
import com.some.pkg.simplemodule.api.*
import com.some.pkg.typesmodule.api.*

data class SomeData(
    private var id: String,
    private var other: OtherData,
    private var custom: Any,
    private var customOpt: Any?,
    private var gDN: String,
    private var defaultValue: String = "customDefaultValue",
) {
    fun getId(): SomeId {
        return SomeId(this.id)
    }

    fun getOther(): OtherData {
        return this.other
    }

    fun getCustom(): Any {
        return this.custom
    }

    fun getCustomOpt(): Any? {
        return this.customOpt
    }

    fun getGoodDataName(): String {
        return this.gDN
    }

    fun getDefaultValue(): SomeOtherId {
        return SomeOtherId(this.defaultValue)
    }

    fun setId(id: SomeId) {
        this.id = id.value
    }

    fun setOther(other: OtherData) {
        this.other = other
    }

    fun setCustom(custom: Any) {
        this.custom = custom
    }

    fun setCustomOpt(customOpt: Any?) {
        this.customOpt = customOpt
    }

    fun setGoodDataName(goodDataName: String) {
        this.gDN = goodDataName
    }

    fun setDefaultValue(defaultValue: SomeOtherId) {
        this.defaultValue = defaultValue.value
    }

    companion object {
        fun create(
            id: SomeId,
            other: OtherData,
            custom: Any,
            customOpt: Any?,
            goodDataName: String,
            defaultValue: SomeOtherId = SomeOtherId("customDefaultValue"),
        ): SomeData {
            return SomeData(
                id = id.value,
                other = other,
                custom = custom,
                customOpt = customOpt,
                gDN = goodDataName,
                defaultValue = defaultValue.value,
            )
        }
    }

    fun update(other: SomeData) {
        this.id = other.id
        this.other = other.other
        this.custom = other.custom
        this.customOpt = other.customOpt
        this.gDN = other.gDN
        this.defaultValue = other.defaultValue
    }
}

data class SomeData2(
    private var optEnum: String?,
    private var optCustomType: String?,
) {
    fun getOptEnum(): SomeEnum? {
        return this.optEnum?.let { it -> SomeEnum.valueOf(it) }
    }

    fun getOptCustomType(): Date? {
        return this.optCustomType?.let { it -> dateCreate(it) }
    }

    fun setOptEnum(optEnum: SomeEnum?) {
        this.optEnum = optEnum?.let { it -> it.name }
    }

    fun setOptCustomType(optCustomType: Date?) {
        this.optCustomType = optCustomType?.let { it -> dateGetValue(it) }
    }

    companion object {
        fun create(
            optEnum: SomeEnum?,
            optCustomType: Date?,
        ): SomeData2 {
            return SomeData2(
                optEnum = optEnum?.let { it -> it.name },
                optCustomType = optCustomType?.let { it -> dateGetValue(it) },
            )
        }
    }

    fun update(other: SomeData2) {
        this.optEnum = other.optEnum
        this.optCustomType = other.optCustomType
    }
}