// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.somemodule.api

import com.some.pkg.moduleonlyformocksargs.api.*
import com.some.pkg.othermodule.api.*
import com.some.pkg.simplemodule.api.*
import com.some.pkg.someusermodule.api.*
import com.some.pkg.typesmodule.api.*

class SomeValueTypeValues {
    companion object {
        val SomeValue = SomeValueType("SomeValue")
        val OtherValue = SomeValueType("OtherValue")
    }
}