// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.somemodule.api

import com.github.bratek20.architecture.events.api.Event

class SomeEvent(
    private val someField: String
): Event {
    fun getSomeField(): String {
        return someField
    }
    companion object {
        fun create(someField: String): SomeEvent {
            return SomeEvent(someField)
        }
    }
}