// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.somemodule.api

import com.some.pkg.othermodule.api.*
import com.some.pkg.typesmodule.api.*

interface SomeInterface {
    @Throws(
        SomeException::class,
        Some2Exception::class,
    )
    fun someCommand(id: SomeId, amount: Int): Unit

    @Throws(
        SomeException::class,
    )
    fun someQuery(id: SomeId): SomeClass

    fun optMethod(optId: SomeId?): SomeClass?
}