// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.somemodule.api

import com.some.pkg.othermodule.api.*
import com.some.pkg.typesmodule.api.*

val SOME_KEY_PROPERTY_KEY = com.github.bratek20.architecture.properties.api.ObjectPropertyKey(
    "SomeKey",
    SomeProperty::class
)

val SOME_SOURCE_PROPERTY_LIST_PROPERTY_KEY = com.github.bratek20.architecture.properties.api.ListPropertyKey(
    "SomeSourcePropertyList",
    SomePropertyEntry::class
)

val SOME_REFERENCING_PROPERTY_OBJECT_PROPERTY_KEY = com.github.bratek20.architecture.properties.api.ObjectPropertyKey(
    "SomeReferencingPropertyObject",
    SomeReferencingProperty::class
)

val SOME_REFERENCING_PROPERTY_LIST_PROPERTY_KEY = com.github.bratek20.architecture.properties.api.ListPropertyKey(
    "SomeReferencingPropertyList",
    SomeReferencingProperty::class
)

val SOME_REFERENCING_PROPERTY_FIELD_LIST_PROPERTY_KEY = com.github.bratek20.architecture.properties.api.ObjectPropertyKey(
    "SomeReferencingPropertyFieldList",
    SomeReferencingPropertyFieldList::class
)

val SOME_STRUCTURE_WITH_UNIQUE_IDS_PROPERTY_KEY = com.github.bratek20.architecture.properties.api.ListPropertyKey(
    "SomeStructureWithUniqueIds",
    SomeStructureWithUniqueIds::class
)

val REFERENCING_OTHER_PROPERTY_PROPERTY_KEY = com.github.bratek20.architecture.properties.api.ObjectPropertyKey(
    "ReferencingOtherProperty",
    OtherProperty::class
)

val OPTIONAL_FIELD_PROPERTIES_PROPERTY_KEY = com.github.bratek20.architecture.properties.api.ListPropertyKey(
    "OptionalFieldProperties",
    OptionalFieldProperty::class
)

val CUSTOM_TYPES_PROPERTY_PROPERTY_KEY = com.github.bratek20.architecture.properties.api.ObjectPropertyKey(
    "CustomTypesProperty",
    CustomTypesProperty::class
)