// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.somemodule.api

import com.some.pkg.othermodule.api.*
import com.some.pkg.typesmodule.api.*

data class SomeProperty(
    val other: OtherProperty,
) {
}

data class SomeProperty2(
    val value: String,
) {
}