// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.somemodule.api

import com.some.pkg.othermodule.api.*
import com.some.pkg.typesmodule.api.*

data class SomeProperty(
    private val other: OtherProperty,
) {
    fun getOther(): OtherProperty {
        return this.other
    }

    companion object {
        fun create(
            other: OtherProperty,
        ): SomeProperty {
            return SomeProperty(
                other = other,
            )
        }
    }
}

data class SomeProperty2(
    private val value: String,
    private val custom: Any,
    private val someEnum: String,
    private val customOpt: Any?,
) {
    fun getValue(): String {
        return this.value
    }

    fun getCustom(): Any {
        return this.custom
    }

    fun getSomeEnum(): SomeEnum {
        return SomeEnum.valueOf(this.someEnum)
    }

    fun getCustomOpt(): Any? {
        return this.customOpt
    }

    companion object {
        fun create(
            value: String,
            custom: Any,
            someEnum: SomeEnum,
            customOpt: Any?,
        ): SomeProperty2 {
            return SomeProperty2(
                value = value,
                custom = custom,
                someEnum = someEnum.name,
                customOpt = customOpt,
            )
        }
    }
}