// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.somemodule.api

import com.some.pkg.othermodule.api.*
import com.some.pkg.typesmodule.api.*

data class SerializedCustomAmountRange(
    private val min: Int,
    private val max: Int,
) {
    fun toCustomType(): CustomAmountRange {
        return customAmountRangeCreate(
            min = customAmountCreate(min),
            max = customAmountCreate(max),
        )
    }

    companion object {
        fun fromCustomType(customType: CustomAmountRange): SerializedCustomAmountRange {
            return SerializedCustomAmountRange(
                min = customAmountGetValue(customAmountRangeGetMin(customType)),
                max = customAmountGetValue(customAmountRangeGetMax(customType)),
            )
        }
    }
}

data class SerializedDateRangeWrapper(
    private val range: SerializedDateRange,
) {
    fun toCustomType(): DateRangeWrapper {
        return dateRangeWrapperCreate(
            range = range.toCustomType(),
        )
    }

    companion object {
        fun fromCustomType(customType: DateRangeWrapper): SerializedDateRangeWrapper {
            return SerializedDateRangeWrapper(
                range = SerializedDateRange.fromCustomType(dateRangeWrapperGetRange(customType)),
            )
        }
    }
}