// DO NOT EDIT! Autogenerated by HLA tool

package src.main.kotlinSkipPatterns.com.some.pkg.othermodule.api

val OTHER_PROPERTY_PROPERTY_KEY = com.github.bratek20.architecture.properties.api.ObjectPropertyKey(
    "otherProperty",
    OtherProperty::class
)

val OTHER_PROPERTIES_PROPERTY_KEY = com.github.bratek20.architecture.properties.api.ListPropertyKey(
    "otherProperties",
    OtherProperty::class
)