// DO NOT EDIT! Autogenerated by HLA tool

namespace SomeModule.Menu {
    export function SomeEmptyInterface() {
    }

    export function SomeInterface() {
    }

    export function SomeInterface2() {
    }

    export function SomeInterface3() {
    }

    export function SomeModuleHandlers() {
    }

    export function SomeModuleDebugHandlers() {
    }

    export function InterfaceForTracking() {
    }
}