// DO NOT EDIT! Autogenerated by HLA tool

namespace OtherModule.Impl {
    export class OtherImplData {
        private name = STRING

        static create(
            name: string,
        ): OtherImplData {
            const instance = new OtherImplData()
            instance.name = name
            return instance
        }

        getName(): string {
            return this.name
        }

        setName(name: string): void {
            this.name = name
        }

        update(other: OtherImplData) {
            this.name = other.name
        }
    }
}