package com.github.bratek20.hla.generation.impl.languages.typescript

import com.github.bratek20.hla.definitions.api.ModuleDefinition
import com.github.bratek20.hla.facade.api.HlaProfile
import com.github.bratek20.hla.facade.api.ModuleLanguage

/**
 * Modern output is opted into twice: the profile decides whether this generation target
 * emits ES modules at all, and each module decides for itself. Both are needed - the same
 * .module files are generated by a legacy and a modern profile side by side, and within
 * one modern profile most modules can still be legacy while a few are migrated.
 */
fun HlaProfile.isModernTypeScript(): Boolean {
    return getLanguage() == ModuleLanguage.TYPE_SCRIPT && getTypeScript()?.getModern() == true
}

fun ModuleDefinition.isMarkedModern(): Boolean {
    return getTypeScriptConfig()?.getModern() == true
}

fun isModernModule(profile: HlaProfile, module: ModuleDefinition): Boolean {
    return profile.isModernTypeScript() && module.isMarkedModern()
}
