package com.github.bratek20.hla.generation.impl.languages.typescript

import com.github.bratek20.hla.definitions.api.ModuleDefinition
import com.github.bratek20.hla.facade.api.HlaProfile
import com.github.bratek20.hla.facade.api.ModuleLanguage

/**
 * Modern output is opted into twice: the profile decides whether this generation target
 * emits ES modules at all, and each module decides for itself. Both are needed - the same
 * .module files are generated by a legacy and a modern profile side by side, and within
 * one modern profile most modules can still be legacy while a few are migrated.
 */
fun HlaProfile.isModernTypeScript(): Boolean {
    return getLanguage() == ModuleLanguage.TYPE_SCRIPT && getTypeScript()?.getModern() == true
}

fun ModuleDefinition.isMarkedModern(): Boolean {
    return getTypeScriptConfig()?.getModern() == true
}

fun isModernModule(profile: HlaProfile, module: ModuleDefinition): Boolean {
    return profile.isModernTypeScript() && module.isMarkedModern()
}

/**
 * Used by startAllModules/updateAllModules to keep an all-modules run from generating a module
 * in the wrong mode: a legacy TypeScript profile would otherwise silently legacy-generate a
 * module meant to be modern, and vice versa. Single-module start/update are unaffected - an
 * explicit request for one module is still honoured regardless of its modern flag.
 */
fun HlaProfile.mismatchesModernFlagOf(module: ModuleDefinition): Boolean {
    if (getLanguage() != ModuleLanguage.TYPE_SCRIPT) {
        return false
    }
    return isModernTypeScript() != module.isMarkedModern()
}
