// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using System.Linq;
using B20.Ext;
using UnityEngine;
using SomeModule.ViewModel;
using B20.View.UiElements.View;
using SomeModule.Api;
using OtherModule.View;
using B20.ViewModel.UiElements.Api;
using OtherModule.Api;

namespace SomeModule.View {
    public class ClassHavingOptSimpleVoView: ElementView<ClassHavingOptSimpleVoVm> {
        [SerializeField]
        OptionalLabelView optSimpleVo;
        protected override void OnBind() {
            base.OnBind();
            optSimpleVo.Bind(ViewModel.OptSimpleVo);
        }
    }
}