// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Elements.View;
using UnityEngine;
using SomeModule.Api;
using SomeModule.ViewModel;
using OtherModule.Api;
using OtherModule.View;
using TypesModule.Api;

namespace SomeModule.View {
    public class SomeClass4View: ElementView<SomeClass4Vm> {
        [SerializeField]
        LabelView otherId;
        [SerializeField]
        OtherClassView otherClass;
        protected override void OnBind() {
            base.OnBind();
            otherId.Bind(ViewModel.OtherId);
            otherClass.Bind(ViewModel.OtherClass);
        }
    }
}