// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using System.Linq;
using B20.Ext;
using B20.View.UiElements;
using UnityEngine;
using SomeModule.Api;
using SomeModule.ViewModel;
using OtherModule.Api;
using OtherModule.ViewModel;
using OtherModule.View;
using TypesModule.Api;

namespace SomeModule.View {
    public class SomeClassView: ElementView<SomeClassVm> {
        [SerializeField]
        LabelView id;
        [SerializeField]
        ButtonView button;
        [SerializeField]
        BoolSwitchView boolSwitch;
        [SerializeField]
        OptionalLabelView optLabel;
        protected override void OnBind() {
            base.OnBind();
            id.Bind(ViewModel.Id);
            button.Bind(ViewModel.Button);
            boolSwitch.Bind(ViewModel.BoolSwitch);
            optLabel.Bind(ViewModel.OptLabel);
        }
    }
}