// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using B20.Ext;
using B20.Frontend.Elements.View;
using UnityEngine;
using SomeModule.ViewModel;
using OtherModule.Api;
using TypesModule.Api;

namespace SomeModule.View {
    public class SomeClass6View: ElementView<SomeClass6Vm> {
        [SerializeField]
        OptionalSomeClassView someClassOpt;
        protected override void OnBind() {
            base.OnBind();
            someClassOpt.Bind(ViewModel.SomeClassOpt);
        }
    }
}