Interfaces
    //incoming
    //there should be InMemorySquadronWarsRepository impl in data submodule and InMemorySquadronWarsData context module
    //also there should be DataTest
    SquadronWarsRepository
        findMatching(warId: SquadronWarId, squadronId: SquadronId): SquadronWarMatchingData?
        //returns entry with empty squadron2
        //there should be at most one such entry
        findMatchingWithEmptySquadron2(warId: SquadronWarId): SquadronWarMatchingData?
        setMatching(matching: SquadronWarMatchingData)