// DO NOT EDIT! Autogenerated by HLA tool

class SomeData {
    private other = new OtherData
    private custom = ANY
    private customOpt? = ANY

    static create(
        other: OtherData,
        custom: any,
        customOpt: Optional<any>,
    ): SomeData {
        const instance = new SomeData()
        instance.other = other
        instance.custom = custom
        instance.customOpt = customOpt.orElse(undefined)
        return instance
    }

    getOther(): OtherData {
        return this.other
    }

    getCustom(): any {
        return this.custom
    }

    getCustomOpt(): Optional<any> {
        return Optional.of(this.customOpt)
    }

    setOther(other: OtherData): void {
        this.other = other
    }

    setCustom(custom: any): void {
        this.custom = custom
    }

    setCustomOpt(customOpt: Optional<any>): void {
        this.customOpt = customOpt.orElse(undefined)
    }
}