// DO NOT EDIT! Autogenerated by HLA tool

interface SomeEmptyInterface {
}
interface SomeInterface {
    /**
     * @throws { SomeException }
     * @throws { Some2Exception }
     */
    someCommand(id: SomeId, amount: number): void

    /**
     * @throws { SomeException }
     */
    someQuery(id: SomeId): SomeClass

    optMethod(optId: Optional<SomeId>): Optional<SomeClass>
}
interface SomeInterface2 {
    referenceInterface(empty: SomeEmptyInterface): SomeEmptyInterface

    referenceOtherInterface(other: OtherInterface): OtherInterface
}