// DO NOT EDIT! Autogenerated by HLA tool

class SomeId {
    constructor(
        public readonly value: string
    ) {}

    equals(other: SomeId): boolean {
        return this.value === other.value
    }

    toString(): string {
        return this.value.toString()
    }
}

class SomeId2 {
    constructor(
        public readonly value: number
    ) {}

    equals(other: SomeId2): boolean {
        return this.value === other.value
    }

    toString(): string {
        return this.value.toString()
    }
}