// DO NOT EDIT! Autogenerated by HLA tool

class SomeEvent extends EventBusNotification {
    constructor(
        private readonly someField: string,
        private readonly otherClass: OtherClass,
        private readonly optField: string | undefined
    ) {
        super()
    }
    getSomeField(): string {
        return this.someField
    }
    getOtherClass(): OtherClass {
        return this.otherClass
    }
    getOptField(): Optional<string> {
        return Optional.of(this.optField)
    }
    getName(): string {
        return "SomeEvent"
    }
    getNotifier(): DependencyName {
        return DependencyName.SomeModule
    }
    static create(someField: string, otherClass: OtherClass, optField: Optional<string>): SomeEvent {
        return new SomeEvent(someField, otherClass, optField.orElse(undefined))
    }
    static createNamed({someField, otherClass, optField, }: {someField: string; otherClass: OtherClass; optField: Optional<string>; }): SomeEvent {
        return new SomeEvent(someField, otherClass, optField.orElse(undefined))
    }
}

class ToNotGenerateInKotlin extends EventBusNotification {
    constructor(
    ) {
        super()
    }
    getName(): string {
        return "ToNotGenerateInKotlin"
    }
    getNotifier(): DependencyName {
        return DependencyName.SomeModule
    }
    static create(): ToNotGenerateInKotlin {
        return new ToNotGenerateInKotlin()
    }
    static createNamed(): ToNotGenerateInKotlin {
        return new ToNotGenerateInKotlin()
    }
}