// DO NOT EDIT! Autogenerated by HLA tool

namespace SomeModule {
    export const SOME_KEY_PROPERTY_KEY = new ObjectPropertyKey(
        "SomeKey",
        SomeProperty
    )

    export const SOME_SOURCE_PROPERTY_LIST_PROPERTY_KEY = new ListPropertyKey(
        "SomeSourcePropertyList",
        SomePropertyEntry
    )

    export const SOME_REFERENCING_PROPERTY_OBJECT_PROPERTY_KEY = new ObjectPropertyKey(
        "SomeReferencingPropertyObject",
        SomeReferencingProperty
    )

    export const SOME_REFERENCING_PROPERTY_LIST_PROPERTY_KEY = new ListPropertyKey(
        "SomeReferencingPropertyList",
        SomeReferencingProperty
    )

    export const REFERENCING_OTHER_PROPERTY_PROPERTY_KEY = new ObjectPropertyKey(
        "ReferencingOtherProperty",
        OtherProperty
    )

    export const OPTIONAL_FIELD_PROPERTIES_PROPERTY_KEY = new ListPropertyKey(
        "OptionalFieldProperties",
        OptionalFieldProperty
    )

    export const CUSTOM_TYPES_PROPERTY_PROPERTY_KEY = new ObjectPropertyKey(
        "CustomTypesProperty",
        CustomTypesProperty
    )
}