// DO NOT EDIT! Autogenerated by HLA tool

class SomeProperty {
    other = new OtherProperty

    static create(
        other: OtherProperty,
    ): SomeProperty {
        const instance = new SomeProperty()
        instance.other = other
        return instance
    }
}

class SomeProperty2 {
    value = STRING
    custom = ANY
    customOpt? = ANY

    static create(
        value: string,
        custom: any,
        customOpt: Optional<any>,
    ): SomeProperty2 {
        const instance = new SomeProperty2()
        instance.value = value
        instance.custom = custom
        instance.customOpt = customOpt.orElse(undefined)
        return instance
    }

    getCustomOpt(): Optional<any> {
        return Optional.of(this.customOpt)
    }
}