// DO NOT EDIT! Autogenerated by HLA tool

using System;
using System.Collections.Generic;
using System.Linq;
using B20.Ext;
using B20.Architecture.Contexts.Api;
using B20.ViewModel.Windows.Api;
using B20.ViewModel.Popups.Api;

namespace OtherModule.ViewModel {
    public class OtherModuleViewModel: ContextModule {
        public void Apply(ContextBuilder builder) {
            builder
                .SetClass<OtherClassVmGroup>(InjectionMode.Prototype)
                .SetClass<OtherClassVm2Group>(InjectionMode.Prototype)
                .SetClass<OptionalOtherClassVm>(InjectionMode.Prototype)
                .SetClass<OtherClassVm>(InjectionMode.Prototype)
                .SetClass<OtherClassVm2>(InjectionMode.Prototype)
                .AddImpl<Popup, OtherPopup>();
        }
    }
}