// DO NOT EDIT! Autogenerated by HLA tool

namespace TypesModule.Builder {
    export interface DateRangeDef {
        from?: string,
        to?: string,
    }
    export function dateRange(def?: DateRangeDef): DateRange {
        const from = def?.from ?? "01/01/1970 00:00"
        const to = def?.to ?? "01/01/2030 00:00"

        return TypesModule.CustomTypesMapper.dateRangeCreate(
            TypesModule.CustomTypesMapper.dateCreate(from),
            TypesModule.CustomTypesMapper.dateCreate(to),
        )
    }
}