Interfaces
    SomeInterface
        someMethod()

    SomeInterface2
        someMethod()

Web
    Http (user)
        ExposedInterfaces
            SomeInterface
            SomeInterface2
        serverName = "someServerName"
        baseUrl = "someService.baseUrl"
        auth = "someService.auth"
        urlPathPrefix = "/some/prefix"
    PlayFabHandlers
        ExposedInterfaces
            SomeInterface
            SomeInterface2 (debug)
        ErrorCodesMapping
            SomeException -> "EC1"
            SomeException2 -> "EC2"
        HandlerNamesMapping
            SomeHandlers.someMethod -> "SomeHandlerName"