Enums
    BaseType
        STRING
        INT
        BOOL
        VOID

    TypeWrapper
        LIST
        OPTIONAL

ValueObjects
    KeyDefinition
        name: string
        type: TypeDefinition

    EnumDefinition
        name: string
        values: string[]

    ImplSubmoduleDefinition
        data: ComplexStructureDefinition[]
        dataKeys: KeyDefinition[]

    ModuleDefinition
        name: ModuleName
        namedTypes: SimpleStructureDefinition[]
        valueObjects: ComplexStructureDefinition[]
        interfaces: InterfaceDefinition[]
        properties: ComplexStructureDefinition[]
        propertyKeys: KeyDefinition[]
        enums: EnumDefinition[]
        simpleCustomTypes: SimpleStructureDefinition[]
        complexCustomTypes: ComplexStructureDefinition[]
        data: ComplexStructureDefinition[]
        dataKeys: KeyDefinition[]
        implSubmodule: ImplSubmoduleDefinition

    TypeDefinition
        name: string
        wrappers: TypeWrapper[]

    FieldDefinition
        name: string
        type: TypeDefinition
        attributes: Attribute[]
        defaultValue: string?

    Attribute
        name: string
        value: string

    SimpleStructureDefinition
        name: string
        typeName: string
        attributes: Attribute[]

    ComplexStructureDefinition
        name: string
        fields: FieldDefinition[]

    InterfaceDefinition
        name: string
        methods: MethodDefinition[]

    ArgumentDefinition
        name: string
        type: TypeDefinition

    ExceptionDefinition
        name: string

    MethodDefinition
        name: string
        returnType: TypeDefinition
        args: ArgumentDefinition[]
        throws: ExceptionDefinition[]