Enums
    BaseType
        STRING
        INT
        BOOL
        VOID
        ANY
        DOUBLE
        LONG
        STRUCT

    TypeWrapper
        LIST
        OPTIONAL

ValueObjects
    KeyDefinition
        name: string
        type: TypeDefinition

    EnumDefinition
        name: string
        values: string[]

    ImplSubmoduleDefinition
        dataClasses: ComplexStructureDefinition[]
        dataKeys: KeyDefinition[]

    WebSubmoduleDefinition
        expose: string[]
        serverUrl: string?

    ExternalTypePackageMapping
        name: string
        packageName: string

    KotlinConfig
        externalTypePackages: ExternalTypePackageMapping[]
        records: string[]

    ModuleDefinition
        name: ModuleName
        simpleCustomTypes: SimpleStructureDefinition[]
        complexCustomTypes: ComplexStructureDefinition[]
        simpleValueObjects: SimpleStructureDefinition[]
        complexValueObjects: ComplexStructureDefinition[]
        dataClasses: ComplexStructureDefinition[]
        interfaces: InterfaceDefinition[]
        propertyKeys: KeyDefinition[]
        dataKeys: KeyDefinition[]
        enums: EnumDefinition[]
        externalTypes: string[]
        implSubmodule: ImplSubmoduleDefinition?
        webSubmodule: WebSubmoduleDefinition?
        kotlinConfig: KotlinConfig?

    TypeDefinition
        name: string
        wrappers: TypeWrapper[]

    FieldDefinition
        name: string
        type: TypeDefinition
        attributes: Attribute[]
        defaultValue: string?

    Attribute
        name: string
        value: string

    SimpleStructureDefinition
        name: string
        typeName: string
        attributes: Attribute[]

    ComplexStructureDefinition
        name: string
        fields: FieldDefinition[]

    InterfaceDefinition
        name: string
        methods: MethodDefinition[]

    ArgumentDefinition
        name: string
        type: TypeDefinition

    ExceptionDefinition
        name: string

    MethodDefinition
        name: string
        returnType: TypeDefinition
        args: ArgumentDefinition[]
        throws: ExceptionDefinition[]