Enums
    BaseType
        STRING
        INT
        BOOL
        VOID
        ANY
        DOUBLE
        LONG
        STRUCT

    TypeWrapper
        LIST
        OPTIONAL

ValueObjects
    KeyDefinition
        name: string
        type: TypeDefinition

    EnumDefinition
        name: string
        values: string[]

    ImplSubmoduleDefinition
        dataClasses: ComplexStructureDefinition[]
        dataKeys: KeyDefinition[]

    HttpDefinition
        exposedInterfaces: string[]
        serverName: string?
        baseUrl: string?
        auth: string?
        urlPathPrefix: string?

    ExposedInterface
        name: string
        attributes: Attribute[]

    ErrorCodeMapping
        exceptionName: string
        code: string

    HandlerNameMapping
        methodPath: string
        handlerName: string

    PlayFabHandlersDefinition
        exposedInterfaces: ExposedInterface[]
        errorCodesMapping: ErrorCodeMapping[]
        handlerNamesMapping: HandlerNameMapping[]

    WebSubmoduleDefinition
        http: HttpDefinition?
        playFabHandlers: PlayFabHandlersDefinition?

    // ViewModel start

    MappedField
        name: string
        mappedName: string? = empty
        mappedType: string? = empty

    DependencyConceptDefinition
        name: string
        mappedFields: MappedField[]

    UiElementDefinition
        name: string
        attributes: Attribute[]
        model: DependencyConceptDefinition?
        fields: FieldDefinition[]

    UiContainerDefinition
        name: string
        state: ComplexStructureDefinition?
        fields: FieldDefinition[]

    ViewModelSubmoduleDefinition
        enumSwitches: string[]
        elements: UiElementDefinition[]
        windows: UiContainerDefinition[]
        popups: UiContainerDefinition[]

    // ViewModel end


    ExternalTypePackageMapping
        name: string
        packageName: string

    KotlinConfig
        externalTypePackages: ExternalTypePackageMapping[]
        records: string[]

    MenuDefinition
        attributes: Attribute[]
        exposedInterfaces: string[]

    ModuleDefinition
        name: ModuleName
        simpleCustomTypes: SimpleStructureDefinition[]
        complexCustomTypes: ComplexStructureDefinition[]
        simpleValueObjects: SimpleStructureDefinition[]
        complexValueObjects: ComplexStructureDefinition[]
        dataClasses: ComplexStructureDefinition[]
        exceptions: ExceptionDefinition[]
        events: ComplexStructureDefinition[]
        interfaces: InterfaceDefinition[]
        propertyKeys: KeyDefinition[]
        dataKeys: KeyDefinition[]
        enums: EnumDefinition[]
        externalTypes: string[]
        implSubmodule: ImplSubmoduleDefinition?
        webSubmodule: WebSubmoduleDefinition?
        viewModelSubmodule: ViewModelSubmoduleDefinition?
        trackingSubmodule: TrackingSubmoduleDefinition?
        fixturesSubmodule: FixturesSubmoduleDefinition?
        kotlinConfig: KotlinConfig?
        menuSubmodule: MenuDefinition?

    FixturesSubmoduleDefinition
        mockedInterfaces: string[]

    TypeDefinition
        name: string
        wrappers: TypeWrapper[]

    FieldDefinition
        name: string
        type: TypeDefinition
        attributes: Attribute[]
        defaultValue: string?

    Attribute
        name: string
        value: string

    SimpleStructureDefinition
        name: string
        typeName: string
        attributes: Attribute[]

    ComplexStructureDefinition
        name: string
        fields: FieldDefinition[]

    InterfaceDefinition
        name: string
        methods: MethodDefinition[]

    ArgumentDefinition
        name: string
        type: TypeDefinition

    ExceptionDefinition
        name: string

    MethodDefinition
        name: string
        returnType: TypeDefinition
        args: ArgumentDefinition[]
        throws: ExceptionDefinition[]