NamedTypes
    ModuleName: string
    ProfileName: string

Enums
    ModuleLanguage
        KOTLIN
        TYPE_SCRIPT

Properties
    "profiles" -> HlaProfile[]
        name: ProfileName
        language: ModuleLanguage
        projectPath: Path
        mainPath: Path
        fixturesPath: Path
        onlyParts: string[]
        generateWeb: bool


ValueObjects
    ModuleOperationArgs
        hlaFolderPath: Path
        profileName: ProfileName
        moduleName: ModuleName

    AllModulesOperationArgs
        hlaFolderPath: Path
        profileName: ProfileName

Interfaces
    HlaFacade
        startModule(args: ModuleOperationArgs)

        updateModule(args: ModuleOperationArgs)

        updateAllModules(args: AllModulesOperationArgs)