Properties
    KotlinProperties
        rootPackage: string

    TypeScriptProperties
        srcPath: string
        testPath: string

    "properties" -> HlaProperties
        generateWeb: bool
        kotlin: KotlinProperties
        typeScript: TypeScriptProperties

Enums
    ModuleLanguage
        KOTLIN
        TYPE_SCRIPT

ValueObjects
    ModuleName: string

    GenerateModuleArgs
        moduleName: ModuleName
        language: ModuleLanguage
        hlaFolderPath: Path
        projectPath: Path

Interfaces
    HlaFacade
        generateModule(args: GenerateModuleArgs)
