NamedTypes
    ModuleName: string
    ProfileName: string

Enums
    ModuleLanguage
        KOTLIN
        TYPE_SCRIPT

Properties
    HlaProfile
        name: ProfileName
        language: ModuleLanguage
        projectPath: string
        srcPath: string
        fixturesPath: string
        onlyParts: string[]

    "properties" -> HlaProperties
        profiles: HlaProfile[]


ValueObjects
    ModuleOperationArgs
        hlaFolderPath: Path
        moduleName: ModuleName
        profileName: ProfileName

Interfaces
    HlaFacade
        startModule(args: ModuleOperationArgs)

        updateModule(args: ModuleOperationArgs)