Enums
    SubmoduleName
        Api
        Impl
        Web
        ViewModel
        View
        Prefabs
        Context
        Fixtures
        Tests
        Examples

    PatternName
        //api
        Primitives
        Enums
        ValueObjects
        DataClasses
        DataKeys
        PropertyKeys
        Interfaces
        Exceptions
        Events
        CustomTypes
        CustomTypesMapper
        SerializedCustomTypes
        Undefined

        //impl
        Logic
        Track
        InitSql
        ImplContext
        //DataClasses - declared in api
        //DataKeys - declared in api

        //web
        WebCommon
        WebServer
        WebClient
        PlayFabHandlers
        WebServerContext
        WebClientContext

        //view model
        GeneratedElements
        ElementsLogic
        GeneratedWindows
        WindowsLogic
        GeneratedPopups
        PopupsLogic
        ViewModelContext

        //view
        ElementsView

        //prefabs
        PrefabBlueprints

        //fixtures
        Builders
        Diffs
        Asserts
        Mocks

        //tests
        ImplTest

        //Examples
        HandlersExamples
        TitleDataExamples
        PlayerDataExamples

ValueObjects
    GeneratedPattern
        name: PatternName
        file: File?
        directory: Directory? //patterns can generate files or directories
    GeneratedSubmodule
        name: SubmoduleName
        patterns: GeneratedPattern[]
    GeneratedModule
        name: ModuleName
        submodules: GeneratedSubmodule[]
Interfaces
    ModuleGenerator
        GenerateArgs
            group: ModuleGroup
            moduleToGenerate: ModuleName
            onlyUpdate: bool
        generate(args: GenerateArgs): GeneratedModule
            throws
                UnknownTypeException