Enums
    PatternName
        //api patterns
        //impl patterns
        Logic
        Data
        //web patterns
        WebCommon
        WebServer
        WebClient
        //context patterns
        Impl
        Web
        //fixtures patterns
        Builders
        Diffs
        Asserts
        //tests patterns
        ImplTest

    SubmoduleName
        Api
        Impl
        Web
        Context
        Fixtures
        Tests

ValueObjects
    GeneratedPattern
        name: PatternName
        content: FileContent
    GeneratedSubmodule
        name: SubmoduleName
        patterns: GeneratedPattern[]
    GeneratedModule
        name: ModuleName
        submodules: GeneratedSubmodule[]
Interfaces
    ModuleGenerator
        GenerateArgs
            group: ModuleGroup
            moduleToGenerate: ModuleName
            onlyUpdate: bool
        generate(args: GenerateArgs): GeneratedModule
            throws
                UnknownTypeException