Enums
    SubmoduleName
        Api
        Impl
        Web
        ViewModel
        View
        Prefabs
        Context
        Fixtures
        Tests

    PatternName
        //api
        Primitives
        Enums
        ValueObjects
        DataClasses
        DataKeys
        PropertyKeys
        Interfaces
        Exceptions
        Events
        CustomTypes
        CustomTypesMapper
        SerializedCustomTypes
        Undefined

        //impl
        Logic
        Track
        InitSql
        //DataClasses - declared in api
        //DataKeys - declared in api

        //web
        WebCommon
        WebServer
        WebClient
        PlayFabHandlers

        //view model
        GeneratedElements
        ElementsLogic
        GeneratedWindows
        WindowsLogic
        GeneratedPopups
        PopupsLogic

        //view
        ElementsView

        //prefabs
        PrefabBlueprints

        //context
        Impl
        Web
        ViewModel

        //fixtures
        Builders
        Diffs
        Asserts
        Mocks

        //tests
        ImplTest

ValueObjects
    GeneratedPattern
        name: PatternName
        file: File
    GeneratedSubmodule
        name: SubmoduleName
        patterns: GeneratedPattern[]
    GeneratedModule
        name: ModuleName
        submodules: GeneratedSubmodule[]
Interfaces
    ModuleGenerator
        GenerateArgs
            group: ModuleGroup
            moduleToGenerate: ModuleName
            onlyUpdate: bool
        generate(args: GenerateArgs): GeneratedModule
            throws
                UnknownTypeException