Enums
    BlueprintType
        ComplexElement
        Window
        ElementGroup
        OptionalElement
        EnumElement

ValueObjects
    PrefabChildBlueprint
        name: string
        viewType: string

    PrefabBlueprint
        blueprintType: BlueprintType
        name: string
        viewType: string
        creationOrder: int
        children: PrefabChildBlueprint[] = [] // only used for UiElement and Window
        elementViewType: string? = empty // only set for ElementGroup and OptionalElement

Interfaces
    PrefabCreatorApi
        startModulePrefabs(modulesPath: string, moduleName: string)
        deleteModulePrefabs(modulesPath: string, moduleName: string)