Enums
    WorldTypeKind
        Primitive
        ClassType
        GenericWrapper
        ConcreteWrapper
        GenericParametrizedClass
        ConcreteParametrizedClass
        //InterfaceType - not needed for now, model for methods will be needed

CustomTypes
    WorldTypePath: string (example: "Some/Path/To/Type")

ExternalTypes
    StructPath

ValueObjects
    WorldTypeName: string

    WorldType
        name: WorldTypeName
        path: WorldTypePath

    WorldClassField
        name: string
        type: WorldType

    WorldClassType
        type: WorldType
        fields: WorldClassField[]
        extends: WorldType? = empty
        //implements: WorldType[] = [] - not needed for now

    WorldConcreteWrapper
        type: WorldType
        wrappedType: WorldType

    WorldConcreteParametrizedClass
        type: WorldType
        typeArguments: WorldType[]

    WorldTypeInfo
        kind: WorldTypeKind

Interfaces
    TypesWorldApi
        // to populate information that such type exits
        // can be called multiple types for the same type
        ensureType(type: WorldType)
            throws
                SameNameTypeExistsException

        hasType(type: WorldType): bool
        hasTypeByName(name: WorldTypeName): bool

        getTypeByName(name: WorldTypeName): WorldType
            throws
                WorldTypeNotFoundException

        getTypeInfo(type: WorldType): WorldTypeInfo
            throws
                WorldTypeNotFoundException

        // to populate more detailed information about type that is used for dependencies calculation
        // all used types are ensured
        addPrimitiveType(type: WorldType)
        addClassType(type: WorldClassType)

        addConcreteParametrizedClass(type: WorldConcreteParametrizedClass)

        //for now List and Optional are hardcoded, in the future it could be handled better by having addGenericWrapper
        //that will add types in format like List<*> or Optional<*>

        getClassType(type: WorldType): WorldClassType
            throws
                WorldTypeNotFoundException

        getConcreteParametrizedClass(type: WorldType): WorldConcreteParametrizedClass
            throws
                WorldTypeNotFoundException

        getConcreteWrapper(type: WorldType): WorldConcreteWrapper
            throws
                WorldTypeNotFoundException

        getTypeDependencies(type: WorldType): WorldType[]
            throws
                WorldTypeNotFoundException

        getAllTypes(): WorldType[]

        getAllReferencesOf(target: WorldType, searchFor: WorldType): StructPath[]
            throws
                SelfReferenceDetectedException

        getAllClassTypes(): WorldClassType[]

Kotlin
    ExternalTypePackages
        StructPath -> com.github.bratek20.architecture.structs.api