Enums
    HlaTypeKind
        Primitive
        ClassType
        GenericWrapper
        ConcreteWrapper
        GenericParametrizedClass
        ConcreteParametrizedClass
        //InterfaceType - not needed for now, model for methods will be needed

CustomTypes
    HlaTypePath: string (example: "SomeRootGroup/SomeNestedGroup/SomeModule/Api/ValueObjects")

ValueObjects
    HlaTypeName: string

    HlaType
        name: HlaTypeName
        path: HlaTypePath

    ClassField
        name: string
        type: HlaType

    ClassType
        type: HlaType
        fields: ClassField[]
        extends: HlaType? = empty
        //implements: HlaType[] = [] - not needed for now

    ConcreteWrapper
        type: HlaType
        wrappedType: HlaType

    ConcreteParametrizedClass
        name: HlaTypeName
        path: HlaTypePath
        typeArguments: HlaType[]

Interfaces
    TypesWorldPopulator
        getOrder(): int // needed as some types are populated from others
        populate(api: TypesWorldApi)

    TypesWorldApi
        populate(populator: TypesWorldPopulator)

        // to populate information that such type exits
        addType(type: HlaType)

        hasType(type: HlaType): bool

        getTypeByName(name: HlaTypeName): HlaType
            throws
                TypeNotFoundException

        // to populate more detailed information about type that is used for dependencies calculation
        addPrimitiveType(type: HlaType)
        addClassType(type: ClassType)
        addConcreteWrapper(type: ConcreteWrapper)
        addConcreteParametrizedClass(type: ConcreteParametrizedClass)

        getClassType(type: HlaType): ClassType
            throws
                TypeNotFoundException

        getTypeDependencies(type: HlaType): HlaType[]

