// DO NOT EDIT! Autogenerated by HLA tool

class ImportingException extends ApiException<ImportingException> {
    constructor(
        message: string = ""
    ) {
        super(ImportingException, message)
    }
    getTypeName(): string {
        return "ImportingException"
    }
}

ExceptionsRegistry.register(ImportingException)