// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.nointerfacesmodule.fixtures

import com.some.pkg.nointerfacesmodule.api.*

fun diffNoInterfaceId(given: NoInterfaceId, expected: String, path: String = ""): String {
    if (given.value != expected) { return "${path}value ${given.value} != ${expected}" }
    return ""
}
