name: Run Tests

permissions:
  checks: write
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: HLA modules test
        uses: bratek20/github-actions/run-tests-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Example modules test
        uses: bratek20/github-actions/run-tests-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project: example


