// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.somemodule.fixtures

import com.some.pkg.somemodule.api.*
import org.assertj.core.api.Assertions.assertThat
import com.some.pkg.othermodule.fixtures.*
import com.some.pkg.othermodule.api.*
import com.some.pkg.simplemodule.fixtures.*
import com.some.pkg.simplemodule.api.*
import com.some.pkg.typesmodule.fixtures.*
import com.some.pkg.typesmodule.api.*

class SomeInterfaceMock: SomeInterface {
    private var someEmptyMethodCallsNumber: Int = 0
    private var someCommandCallsNumber: Int = 0
    private val someCommandCalls: List<(SomeInterfaceSomeCommandArgsDef.() -> Unit)> = emptyList()
    private var someQueryCallsNumber: Int = 0
    private val someQueryCalls: List<(SomeQueryInputDef.() -> Unit)> = emptyList()
    private var someQueryResponse: (SomeClassDef.() -> Unit) = {}
    private var optMethodCallsNumber: Int = 0
    private val optMethodCalls: List<String?> = emptyList()
    private var optMethodResponse: (SomeClassDef.() -> Unit)? = null
    private var methodWithListOfSimpleVOCallsNumber: Int = 0
    private val methodWithListOfSimpleVOCalls: List<List<String>> = emptyList()
    private var methodWithListOfSimpleVOResponse: List<String> = emptyList()
    private var methodWithAnyCallsNumber: Int = 0
    private val methodWithAnyCalls: List<Any> = emptyList()
    private var methodWithAnyResponse: Any = {}
    private var methodReturningOptSimpleVoCallsNumber: Int = 0
    private var methodReturningOptSimpleVoResponse: String? = null
    private var methodReturningNumericTypeCallsNumber: Int = 0
    private var methodReturningNumericTypeResponse: Int = 0
    override fun someEmptyMethod(): Unit {
        someEmptyMethodCallsNumber = someEmptyMethodCallsNumber + 1
    }
    fun assertSomeEmptyMethodCallsNumber(expectedNumber: Int) {
        assertThat(someEmptyMethodCallsNumber).withFailMessage("Expected 'someEmptyMethod' to be called " + expectedNumber + " times but was called " + someEmptyMethodCallsNumber + " times").isEqualTo(expectedNumber)
    }
    override fun someCommand(id: SomeId, amount: Int): Unit {
        someCommandCallsNumber = someCommandCallsNumber + 1
    }
    fun assertSomeCommandCallsNumber(expectedNumber: Int) {
        assertThat(someCommandCallsNumber).withFailMessage("Expected 'someCommand' to be called " + expectedNumber + " times but was called " + someCommandCallsNumber + " times").isEqualTo(expectedNumber)
    }
    override fun someQuery(query: SomeQueryInput): SomeClass {
        someQueryCallsNumber = someQueryCallsNumber + 1
        return someClass(someQueryResponse)
    }
    fun assertSomeQueryCallsNumber(expectedNumber: Int) {
        assertThat(someQueryCallsNumber).withFailMessage("Expected 'someQuery' to be called " + expectedNumber + " times but was called " + someQueryCallsNumber + " times").isEqualTo(expectedNumber)
    }
    fun setSomeQueryResponse(response: (SomeClassDef.() -> Unit)) {
        someQueryResponse = response
    }
    override fun optMethod(optId: SomeId?): SomeClass? {
        optMethodCallsNumber = optMethodCallsNumber + 1
        return optMethodResponse?.let { it -> someClass(it) }
    }
    fun assertOptMethodCallsNumber(expectedNumber: Int) {
        assertThat(optMethodCallsNumber).withFailMessage("Expected 'optMethod' to be called " + expectedNumber + " times but was called " + optMethodCallsNumber + " times").isEqualTo(expectedNumber)
    }
    fun setOptMethodResponse(response: (SomeClassDef.() -> Unit)?) {
        optMethodResponse = response
    }
    override fun methodWithListOfSimpleVO(list: List<SomeId>): List<SomeId> {
        methodWithListOfSimpleVOCallsNumber = methodWithListOfSimpleVOCallsNumber + 1
        return methodWithListOfSimpleVOResponse.map { it -> SomeId(it) }
    }
    fun assertMethodWithListOfSimpleVOCallsNumber(expectedNumber: Int) {
        assertThat(methodWithListOfSimpleVOCallsNumber).withFailMessage("Expected 'methodWithListOfSimpleVO' to be called " + expectedNumber + " times but was called " + methodWithListOfSimpleVOCallsNumber + " times").isEqualTo(expectedNumber)
    }
    fun setMethodWithListOfSimpleVOResponse(response: List<String>) {
        methodWithListOfSimpleVOResponse = response
    }
    override fun methodWithAny(i: Any): Any {
        methodWithAnyCallsNumber = methodWithAnyCallsNumber + 1
        return methodWithAnyResponse
    }
    fun assertMethodWithAnyCallsNumber(expectedNumber: Int) {
        assertThat(methodWithAnyCallsNumber).withFailMessage("Expected 'methodWithAny' to be called " + expectedNumber + " times but was called " + methodWithAnyCallsNumber + " times").isEqualTo(expectedNumber)
    }
    fun setMethodWithAnyResponse(response: Any) {
        methodWithAnyResponse = response
    }
    override fun methodReturningOptSimpleVo(): SomeId? {
        methodReturningOptSimpleVoCallsNumber = methodReturningOptSimpleVoCallsNumber + 1
        return methodReturningOptSimpleVoResponse?.let { it -> SomeId(it) }
    }
    fun assertMethodReturningOptSimpleVoCallsNumber(expectedNumber: Int) {
        assertThat(methodReturningOptSimpleVoCallsNumber).withFailMessage("Expected 'methodReturningOptSimpleVo' to be called " + expectedNumber + " times but was called " + methodReturningOptSimpleVoCallsNumber + " times").isEqualTo(expectedNumber)
    }
    fun setMethodReturningOptSimpleVoResponse(response: String?) {
        methodReturningOptSimpleVoResponse = response
    }
    override fun methodReturningNumericType(): Int {
        methodReturningNumericTypeCallsNumber = methodReturningNumericTypeCallsNumber + 1
        return methodReturningNumericTypeResponse
    }
    fun assertMethodReturningNumericTypeCallsNumber(expectedNumber: Int) {
        assertThat(methodReturningNumericTypeCallsNumber).withFailMessage("Expected 'methodReturningNumericType' to be called " + expectedNumber + " times but was called " + methodReturningNumericTypeCallsNumber + " times").isEqualTo(expectedNumber)
    }
    fun setMethodReturningNumericTypeResponse(response: Int) {
        methodReturningNumericTypeResponse = response
    }
    fun reset() {
        someEmptyMethodCallsNumber = 0
        someCommandCallsNumber = 0
        someCommandCalls = emptyList()
        someQueryCallsNumber = 0
        someQueryCalls = emptyList()
        someQueryResponse = {}
        optMethodCallsNumber = 0
        optMethodCalls = emptyList()
        optMethodResponse = null
        methodWithListOfSimpleVOCallsNumber = 0
        methodWithListOfSimpleVOCalls = emptyList()
        methodWithListOfSimpleVOResponse = emptyList()
        methodWithAnyCallsNumber = 0
        methodWithAnyCalls = emptyList()
        methodWithAnyResponse = {}
        methodReturningOptSimpleVoCallsNumber = 0
        methodReturningOptSimpleVoResponse = null
        methodReturningNumericTypeCallsNumber = 0
        methodReturningNumericTypeResponse = 0
    }
}

class SomeInterface2Mock: SomeInterface2 {
    private var referenceOtherClassCallsNumber: Int = 0
    private val referenceOtherClassCalls: List<(OtherClassDef.() -> Unit)> = emptyList()
    private var referenceOtherClassResponse: (OtherClassDef.() -> Unit) = {}
    private var referenceLegacyTypeCallsNumber: Int = 0
    private val referenceLegacyTypeCalls: List<com.some.pkg.legacy.LegacyType> = emptyList()
    override fun referenceOtherClass(other: OtherClass): OtherClass {
        referenceOtherClassCallsNumber = referenceOtherClassCallsNumber + 1
        return otherClass(referenceOtherClassResponse)
    }
    fun assertReferenceOtherClassCallsNumber(expectedNumber: Int) {
        assertThat(referenceOtherClassCallsNumber).withFailMessage("Expected 'referenceOtherClass' to be called " + expectedNumber + " times but was called " + referenceOtherClassCallsNumber + " times").isEqualTo(expectedNumber)
    }
    fun setReferenceOtherClassResponse(response: (OtherClassDef.() -> Unit)) {
        referenceOtherClassResponse = response
    }
    override fun referenceLegacyType(legacyType: com.some.pkg.legacy.LegacyType): com.some.pkg.legacy.LegacyType {
        referenceLegacyTypeCallsNumber = referenceLegacyTypeCallsNumber + 1
        return TODO()
    }
    fun assertReferenceLegacyTypeCallsNumber(expectedNumber: Int) {
        assertThat(referenceLegacyTypeCallsNumber).withFailMessage("Expected 'referenceLegacyType' to be called " + expectedNumber + " times but was called " + referenceLegacyTypeCallsNumber + " times").isEqualTo(expectedNumber)
    }
    fun reset() {
        referenceOtherClassCallsNumber = 0
        referenceOtherClassCalls = emptyList()
        referenceOtherClassResponse = {}
        referenceLegacyTypeCallsNumber = 0
        referenceLegacyTypeCalls = emptyList()
    }
}

class SomeModuleHandlersMock: SomeModuleHandlers {
    private var someHandlerCallsNumber: Int = 0
    private val someHandlerCalls: List<(SomeHandlerInputDef.() -> Unit)> = emptyList()
    private var someHandlerResponse: (SomeHandlerOutputDef.() -> Unit) = {}
    private var someHandler2CallsNumber: Int = 0
    private val someHandler2Calls: List<(SomeHandlerInputDef.() -> Unit)> = emptyList()
    private var someHandler2Response: (SomeHandlerOutputDef.() -> Unit) = {}
    override fun someHandler(i: SomeHandlerInput): SomeHandlerOutput {
        someHandlerCallsNumber = someHandlerCallsNumber + 1
        return someHandlerOutput(someHandlerResponse)
    }
    fun assertSomeHandlerCallsNumber(expectedNumber: Int) {
        assertThat(someHandlerCallsNumber).withFailMessage("Expected 'someHandler' to be called " + expectedNumber + " times but was called " + someHandlerCallsNumber + " times").isEqualTo(expectedNumber)
    }
    fun setSomeHandlerResponse(response: (SomeHandlerOutputDef.() -> Unit)) {
        someHandlerResponse = response
    }
    override fun someHandler2(i: SomeHandlerInput): SomeHandlerOutput {
        someHandler2CallsNumber = someHandler2CallsNumber + 1
        return someHandlerOutput(someHandler2Response)
    }
    fun assertSomeHandler2CallsNumber(expectedNumber: Int) {
        assertThat(someHandler2CallsNumber).withFailMessage("Expected 'someHandler2' to be called " + expectedNumber + " times but was called " + someHandler2CallsNumber + " times").isEqualTo(expectedNumber)
    }
    fun setSomeHandler2Response(response: (SomeHandlerOutputDef.() -> Unit)) {
        someHandler2Response = response
    }
    fun reset() {
        someHandlerCallsNumber = 0
        someHandlerCalls = emptyList()
        someHandlerResponse = {}
        someHandler2CallsNumber = 0
        someHandler2Calls = emptyList()
        someHandler2Response = {}
    }
}

class SomeModuleDebugHandlersMock: SomeModuleDebugHandlers {
    private var someDebugHandlerCallsNumber: Int = 0
    private val someDebugHandlerCalls: List<(SomeHandlerInputDef.() -> Unit)> = emptyList()
    private var someDebugHandlerResponse: (SomeHandlerOutputDef.() -> Unit) = {}
    private var someDebugHandler2CallsNumber: Int = 0
    private val someDebugHandler2Calls: List<(SomeHandlerInputDef.() -> Unit)> = emptyList()
    private var someDebugHandler2Response: (SomeHandlerOutputDef.() -> Unit) = {}
    override fun someDebugHandler(i: SomeHandlerInput): SomeHandlerOutput {
        someDebugHandlerCallsNumber = someDebugHandlerCallsNumber + 1
        return someHandlerOutput(someDebugHandlerResponse)
    }
    fun assertSomeDebugHandlerCallsNumber(expectedNumber: Int) {
        assertThat(someDebugHandlerCallsNumber).withFailMessage("Expected 'someDebugHandler' to be called " + expectedNumber + " times but was called " + someDebugHandlerCallsNumber + " times").isEqualTo(expectedNumber)
    }
    fun setSomeDebugHandlerResponse(response: (SomeHandlerOutputDef.() -> Unit)) {
        someDebugHandlerResponse = response
    }
    override fun someDebugHandler2(i: SomeHandlerInput): SomeHandlerOutput {
        someDebugHandler2CallsNumber = someDebugHandler2CallsNumber + 1
        return someHandlerOutput(someDebugHandler2Response)
    }
    fun assertSomeDebugHandler2CallsNumber(expectedNumber: Int) {
        assertThat(someDebugHandler2CallsNumber).withFailMessage("Expected 'someDebugHandler2' to be called " + expectedNumber + " times but was called " + someDebugHandler2CallsNumber + " times").isEqualTo(expectedNumber)
    }
    fun setSomeDebugHandler2Response(response: (SomeHandlerOutputDef.() -> Unit)) {
        someDebugHandler2Response = response
    }
    fun reset() {
        someDebugHandlerCallsNumber = 0
        someDebugHandlerCalls = emptyList()
        someDebugHandlerResponse = {}
        someDebugHandler2CallsNumber = 0
        someDebugHandler2Calls = emptyList()
        someDebugHandler2Response = {}
    }
}