// DO NOT EDIT! Autogenerated by HLA tool

package com.some.pkg.simplemodule.fixtures

import com.some.pkg.simplemodule.api.*

fun diffSimpleId(given: SimpleId, expected: String, path: String = ""): String {
    if (given.value != expected) { return "${path}value ${given.value} != ${expected}" }
    return ""
}
