// DO NOT EDIT! Autogenerated by HLA tool

import { SomeUserValueObject } from "../../../main/SomeUserModule/Api/ValueObjects"
import { ExpectedSomeUserValueObject, diffSomeUserValueObject } from "./Diffs"

export function someUserValueObject(given: SomeUserValueObject, expected: ExpectedSomeUserValueObject) {
    const diff = diffSomeUserValueObject(given, expected)
    AssertEquals(diff, "", diff)
}
