// DO NOT EDIT! Autogenerated by HLA tool

namespace WebNoWrappers.Assert {
    export function webRequest(given: WebRequest, expected: ExpectedWebRequest) {
        const diff = diffWebRequest(given, expected)
        AssertEquals(diff, "", diff)
    }

    export function webResult(given: WebResult, expected: ExpectedWebResult) {
        const diff = diffWebResult(given, expected)
        AssertEquals(diff, "", diff)
    }
}